### ISSUE TITLE
FreeSurfer 6.0.1

### ISSUE THREAD

**Issue by effigies** [ReproNim/neurodocker#114]
FreeSurfer just released [6.0.1](https://ftp.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.1/), which is just 6.0.0 with the ability to specify the location of a LICENSE file as an environment variable (https://github.com/freesurfer/freesurfer/compare/release_6_0_0...stable6), which was added to make containerized FreeSurfer easier to use without baking in a license.

I know NeuroDocker's done some work on handling licenses already, but I wanted to know if you were aware of this release and planning to add support in the near future?

**Comment by kaczmarj** [comment]
@effigies - thanks for letting me know. It should already be possible to generate a Dockerfile with FreeSurfer 6.0.1. How does the command below look to you? Is it fair to expect users to set `FS_LICENSE` explicitly, or should that be abstracted (for example `--freesurfer version =6.0.1 license=/path/in/container/license.txt`)?

At the moment, there is a `license_path` option for freesurfer accepts a path on the local machine to be copied into the container.

```
docker run --rm kaczmarj/neurodocker:master generate -b debian:stretch -p apt \
--freesurfer version=6.0.1 -e FS_LICENSE=/path/to/license.txt
```

**Comment by effigies** [comment]
I'm not really sure how best to handle it. We're not using neurodocker yet, so I haven't formulated any opinions. Sorry if this is a kind of useless issue, then.

Also, I was kind of thinking in terms of updating the minimized version of FreeSurfer, but I've realized that we probably can't use that as is, anyway (we need fsaverage5).

Feel free to close, if this issue isn't flagging useful things for you to do.

**Comment by kaczmarj** [comment]
I agree, it would be nice to minimize FreeSurfer 6.0.1. I'll leave this issue up until that happens. I can try to do it this weekend.

**Comment by djarecka** [comment]
@kaczmarj - do you still think that `FS_LICENSE` should be added as an additional argument?  I can see that you included some options how to deal with it in [the known issues](https://www.repronim.org/neurodocker/user_guide/known_issues.html)

**Comment by kaczmarj** [comment]
In the current implementation, we ask the user to use a —copy instruction and an —env instruction, right?I am personally fine with leaving it that way. What do you think Dorota?Best,JakubOn Feb 3, 2023, at 15:14, Dorota Jarecka ***@***.***> wrote:﻿
@kaczmarj - do you still think that FS_LICENSE should be added as an additional argument?  I can see that you included some options how to deal with it in the known issues

**Comment by djarecka** [comment]
Do you have an example? In the FreeSurfer [example page](https://www.repronim.org/neurodocker/user_guide/examples.html) there is no usage of `--env`

**Comment by djarecka** [comment]
closing it now, please feel free to reopen
