### ISSUE TITLE
Request: Jupyter/JupyterLab

### ISSUE THREAD

**Issue by effigies** [ReproNim/neurodocker#146]
Having Neurodocker do the work of properly setting up and configuring JupyterLab would be pretty handy in terms of getting an interactive sandbox going as quickly as possible. I think it fits into the existing structure (`/work` working directory, `neuro` user) pretty naturally, but a default configuration (and, optionally, setting the `ENTRYPOINT`) would make things that much smoother.

**Comment by kaczmarj** [comment]
@effigies - can you elaborate? Would this only be if a user installs jupyter?
