### ISSUE TITLE
minimize space by choosing optimal libraries, removing source files, etc.,.

### ISSUE THREAD

**Issue by satra** [ReproNim/neurodocker#177]
as an example, the tensorflow docker image is tiny relative to any tensorflow image we may produce with miniconda or some such. 

- dynamically linked binaries are going to reduce space for FSL/ANTs/AFNI etc.,. so we need to figure out recipes to build those from source across at least a few OSes
- the additions for the build process itself should not be in a container post build. so i think every build recipe should have a `-pre`, `-build`, and `-post` section to help with cleanup.

just some thoughts here as we try to optimize container sizes, and build steps.

**Comment by djarecka** [comment]
@kaczmarj - do you think this might be still useful? should we close it?

**Comment by kaczmarj** [comment]
Let’s close this. the goal here is quite broad. In the future if this is still interesting, we can open a new issue with concrete goals.On Feb 3, 2023, at 15:29, Dorota Jarecka ***@***.***> wrote:﻿
@kaczmarj - do you think this might be still useful? should we close it?
