### ISSUE TITLE
Non-free license agreement

### ISSUE THREAD

**Issue by effigies** [ReproNim/neurodocker#188]
There may be issues with regard to automatically installing FSL and other non-free software without displaying (and perhaps prompting for acknowledgment?) of the license agreement.

I acknowledge that it's in the docs, but programmatic installation of software may require more active measures.

**Comment by kaczmarj** [comment]
Good point. Do you know how neurodebian handles that? As far as I know, users aren’t prompted about the non-free license agreements. Though, they do have to actively use the non-free apt sources.

**Comment by kaczmarj** [comment]
I do take care to alert the user that FSL is non-free, when they enter a container with fsl installed through neurodocker (not neurodebian).

https://github.com/kaczmarj/neurodocker/blob/70748f5009dc9fcf74de6a7f2606e45620ace16e/neurodocker/templates/fsl.yaml#L30-L32

**Comment by djarecka** [comment]
i think this is coverage indifferent issues
