### ISSUE TITLE
new minc version

### ISSUE THREAD

**Issue by stebo85** [ReproNim/neurodocker#192]
Dear Jakub,

There is a new minc version 1.9.16. The current version in neurodocker (1.9.15) also has missing libraries for the visual tools, like register.

This is the singularity buildscript from Vladimir S. Fonov that creates a perfectly working singularity container - would it be worth integrating this in neurdocker? 

#Bootstrap: localimage
#From: /home/vfonov/src/minc-toolkit-containers/singularity/minc-toolkit-base.simg
Bootstrap: shub
From: vfonov/minc-toolkit-containers:base

# install minc packages
%post
    # update locales
    locale-gen en_US.UTF-8 en_US en_CA.UTF-8 en_CA
    dpkg-reconfigure locales

    # install minc-toolkit 1.9.16
    wget http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
    dpkg -i minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
    rm -f minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb 
    wget http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/beast-library-1.1.0-20121212.deb 
    dpkg -i beast-library-1.1.0-20121212.deb 
    rm -f beast-library-1.1.0-20121212.deb 
    wget http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/bic-mni-models-0.1.1-20120421.deb 
    dpkg -i bic-mni-models-0.1.1-20120421.deb 
    rm -f bic-mni-models-0.1.1-20120421.deb
    
    apt-get autoclean 
    rm -rf /var/lib/apt/lists/*
    
    
    # install RMINC
    . /opt/minc/1.9.16/minc-toolkit-config.sh && \
    wget https://github.com/Mouse-Imaging-Centre/RMINC/releases/download/v1.5.1.0/RMINC_1.5.1.0.tar.gz && \
    R CMD INSTALL RMINC_1.5.1.0.tar.gz --configure-args='--with-build-path=/opt/minc/1.9.16' && \
    rm -f RMINC_1.5.1.0.tar.gz

    # install pyezminc, pyminc, minc2-simple
    . /opt/minc/1.9.16/minc-toolkit-config.sh && \
    pip install pyminc --no-cache-dir && \
    wget https://github.com/BIC-MNI/pyezminc/archive/release-1.2.01.tar.gz && \
    pip install release-1.2.01.tar.gz --no-cache-dir && \
    wget https://github.com/vfonov/minc2-simple/archive/v0.tar.gz && \
    tar zxf v0.tar.gz && \
    python minc2-simple-0/python/setup.py install && \
    rm -rf v0.tar.gz release-1.2.01.tar.gz minc2-simple-0 
    
    echo ". /opt/minc/1.9.16/minc-toolkit-config.sh" >> $SINGULARITY_ENVIRONMENT
    

%labels
    Maintainer Vladimir S. Fonov
    AUTHOR vladimir.fonov@gmail.com
    Version 1.9.16

**Comment by kaczmarj** [comment]
thank you @stebo85. 

it would absolutely be worth integrating this work into neurodocker. i am hoping to support as many neuroimaging packages as possible.

vladimir s. fonov is using the `.deb` format to install minc toolkit, beast library, and models. the installation instructions would have to be more general than that for neurodocker to support non-deb linux distributions (e.g., centos, fedora, which use `.rpm`). to get around this, i contributed a [Dockerfile](https://github.com/BIC-MNI/build_packages/blob/master/build_centos_6.9_x64/Dockerfile) way back to build minc toolkit on centos 6, which should make it compatible with most linux distributions after 2012. to include the new version of minc toolkit, i would prefer to build it in centos 6, host those compiled binaries on the web, and install them on any base system a neurodocker user chooses. neurodocker currently does this (see https://github.com/kaczmarj/neurodocker/pull/79).

i would prefer not to install the python packages pyezminc, pyminc, and minc2-simple when installing minc with `--minc`. instead, i would leave it to the user to install these packages with `--miniconda`.

like i said in the other issue, i won't have time work on this for several days, but if you are up for it, you can absolutely submit a pull request to add this.

**Comment by stebo85** [comment]
hi @kaczmarj, I can try and see how far I get, but I am still quite new to playing with these things, so no big hopes on me ... as an alternative to your suggestion, would it be an option to compile minc from source like you do it with dcm2niix or do you think this takes too long for minc?

**Comment by kaczmarj** [comment]
@stebo85 - yes an option to compile minc would be great, and we can already draw from https://github.com/BIC-MNI/build_packages. i forget how long the compilation takes, but it would be nice to at least have the option to compile.

i will try to compile the new minc version on centos 6 soon.

**Comment by kaczmarj** [comment]
hi @stebo85 - compiled minc toolkit v2 version 1.9.16 https://www.dropbox.com/s/u9ksy2zfqmytz3x/minc-toolkit-1.9.16-20180117-CentOS_6.10-x86_64.tar.gz

would you like to submit a pr that adds the link to https://github.com/kaczmarj/neurodocker/blob/5bc7dc74a9609094b783d858c93e0743be7edec7/neurodocker/templates/minc.yaml#L12

the link should be https://dl.dropbox.com/s/u9ksy2zfqmytz3x/minc-toolkit-1.9.16-20180117-CentOS_6.10-x86_64.tar.gz (that downloads immediately, the first link i shared does not download immediately).

**Comment by stebo85** [comment]
Hi @kaczmarj, I am working on this now. Will send pr as soon as the new minc version is tested and works :)

**Comment by djarecka** [comment]
@stebo85 - are you still working on it?

**Comment by stebo85** [comment]
I send the pull request, but it was never merged.

**Comment by djarecka** [comment]
closed with #509
