### ISSUE TITLE
Please include in the header (or trailer) of the generated file the original cmdline args used to generate it

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#213]
thought to send a PR but couldn't find a least intrusive non-ugly way to accomplish the mission.

It is common to keep produced Singularity/Docker-file etc within VCS, but it is not as common to store the actual command used to produce them.  So I thought that if Neurodocker embedded the list of the original sys.argv's used, it could come really handy at times.

**Comment by kaczmarj** [comment]
this is a great idea, thank you. i will try to implement this soon.

**Comment by djarecka** [comment]
@kaczmarj - is this still relevant?

**Comment by djarecka** [comment]
i think we still don't have it and it might be nice to add it

**Comment by kaczmarj** [comment]
i also believe we don't have it and it would be nice to add.
