### ISSUE TITLE
Error building conda_python example

### ISSUE THREAD

**Issue by nataliavelez** [ReproNim/neurodocker#222]
Dear all,

I tried creating a Singularity image using the conda_python example in this repository, but the process gets killed near the end. This is the command I used to build the Singularity recipe:

```
docker run --rm kaczmarj/neurodocker:master generate singularity \
	--base=neurodebian:stretch-non-free \
	--pkg-manager=apt \
	--install vim emacs-nox \
	--user=neuro \
	--miniconda \
		  conda_install="python=3.6 jupyter jupyterlab jupyter_contrib_nbextensions
		                 matplotlib scikit-learn seaborn" \
		  pip_install="nilearn" \
		  create_env="neuro_py36" \
		  activate=true \
	--run 'mkdir -p ~/.jupyter && echo c.NotebookApp.ip = \"0.0.0.0\" > ~/.jupyter/jupyter_notebook_config.py' \
	--workdir /home/neuro > $singularity_file
```

It's the same as the original example. However, I get this error:

```
## Package Plan ##

  environment location: /opt/miniconda-latest/envs/neuro_py36


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ conda install -y -q --name neuro_py36 python=3.6 jupyter jupyterlab jupyter_contrib_nbextensions matplotlib scikit-learn seaborn
Solving environment: ...working... Killed
ABORT: Aborting with RETVAL=255
Cleaning up...
```
I'm new to neurodocker, so any tips on how to troubleshoot this would be appreciated.

Thanks,
Natalia

**Comment by kaczmarj** [comment]
hi @nataliavelez - i am able to run this neurodocker command with singularity version 2.5.2. it looks like your build was killed for some reason (`Solving environment: ...working... Killed`). can you give me more information about your setup?

- output of `docker run --rm kaczmarj/neurodocker:master --version`
- output of `singularity --version`
- linux version (`uname -a`)

can you also try to rebuild the singularity image with the `--debug` flag in the `singularity build` command? you should delete or move the previous singularity image before rebuilding.

**Comment by kaczmarj** [comment]
@nataliavelez - i will close this issue, but please reopen if you want to discuss more.
