### ISSUE TITLE
Brainsuite

### ISSUE THREAD

**Issue by infinitejest** [ReproNim/neurodocker#225]
I been fighting to integrate neurodocker custom dockerfile with the software brainsuite without sucess. Is it possible that you add Brainsuite as part of the neurodocker installation menu. 

Dockerfile: 
https://github.com/BIDS-Apps/BrainSuite/blob/master/Dockerfile

Brainsuite Website: 
http://brainsuite.org/

**Comment by djarecka** [comment]
if there is still interest in this, please feel free to reopen
