### ISSUE TITLE
Latest version of ANTS needs cmake 3.10 to compile

### ISSUE THREAD

**Issue by Gilles86** [ReproNim/neurodocker#226]
I was trying to make a Neurodocker with the latest version of [ants](https://github.com/ANTsX/ANTs)

However, when I use 
> --ants --method=source version=latest

It starts complaining when the Docker image start compiling, because the cmake is too old
> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
>  CMake 3.10.2 or higher is required.  You are running version 3.7.2

This can be solved by installing the latest cmake by something like this:
> RUN wget -qO- "https://cmake.org/files/v3.12/cmake-3.12.2-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C /usr/local

However, maybe this newer cmake interrupts with other software? What is the best way to go here? Maybe compile cmake to some temp directory and use that version for compiling ANTS?

**Comment by Gilles86** [comment]
By the way: I need this to use the latest syntax of MeasureImageSimilarity.

Maybe it would be good to also includes builds of 2.3.0 and 2.3.1:
https://github.com/ANTsX/ANTs/releases

So whose Dropbox are 2.0.0, 2.1.0, etc in?

**Comment by kaczmarj** [comment]
hi @Gilles86 - using a temporary cmake is a great idea. would you like to add that?

i recently built versions 2.3.1 and 2.3.0 of ANTs here: https://github.com/kaczmarj/ANTs-builds/tree/add/versions. that is my dropbox by the way. we can add those versions to the prebuilt binaries in neurodocker.

**Comment by djarecka** [comment]
is this still an issue or can we close it?

**Comment by Remi-Gau** [comment]
Given that ants docker images are all buildable in CI with all versions I would say that this is no longer an issue.
