### ISSUE TITLE
Enable generation of Alpine Linux-based images

### ISSUE THREAD

**Issue by effigies** [ReproNim/neurodocker#230]
This is kind of a stretch goal, but it might be nice to enable [Alpine](https://hub.docker.com/_/alpine/)-based images, which use the `apk` package manager. The base image is 5MiB, and if we're interested in eventually distributing containers to run sub-components of nipype workflows (e.g. in niflows), then smaller base containers might become useful.

**Comment by kaczmarj** [comment]
@effigies - yes i was considering this. i think in most cases, `glibc` will have to be installed in alpine containers for most of neurodocker's use cases.

i wouldn't call this a stretch! and using alpine for sub-components of nipype workflows is an excellent use case. if one used alpine as a base image for, say, freesurfer, the small size of alpine is irrelevant relative to the huge size of freesurfer. but with small sub-component of workflows, alpine becomes much more reasonable.

it would be good to test this out with something like fsl or minimized freesurfer recon-all to make sure that these programs can run on alpine. alpine uses `musl`, whereas those programs likely use `glibc`. `glibc` can be installed on alpine, but i wonder whether shared libraries installed with `apk` will work with fsl, freesurfer, etc.

**Comment by kaczmarj** [comment]
i will close this issue for now as it's gone stale
