### ISSUE TITLE
Creation of a detailed software summary within the docker image

### ISSUE THREAD

**Issue by miykael** [ReproNim/neurodocker#232]
Currently, `neurodocker` creates a `neurodocker_specs.json` file that contains the information to create a specific neurodocker image. Thinking about reproducibility and [`niflows`](https://github.com/niflows), would it make sense to have an additional summary file that reports all the software (with version number) installed in a given docker container?

Something like this could easily be published with the source code and add to transparency.

**Comment by kaczmarj** [comment]
this sounds like a great use case for [NICEMAN](https://github.com/ReproNim/niceman/) within neurodocker! that should give a detailed description of everything inside the container.

**Comment by miykael** [comment]
I assume that we're interested in the `- ls (List known computation resources, images and environments)` command of `niceman`?

For this to work, you need to specify a `config.cfg` file. Do you have such an example or a quick example code on how to use `niceman` in the `neurodocker` framework?

Also, am I correct that such a functionality would need to be implemented in https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/generators/common.py?

**Comment by djarecka** [comment]
@kaczmarj - I believe this was implemented somewhere, am I right?

**Comment by djarecka** [comment]
if there is still interest in this, please feel free to reopen
