### ISSUE TITLE
startup.sh vs .singularity.d/env/ as a way to do environment vars setup

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#242]
ATM neurodocker adds `source /etc/fsl/5.0/fsl.sh` to the `/neurodocker/startup.sh` to do necessary tune ups to the env vars fsl needs.  Although it is  in effect for `run`

```shell
$> singularity run .datalad/environments/fsl/image export | grep FSLDIR
declare -x FSLDIR="/usr/share/fsl/5.0"
```
it is not in effect for `exec` which doesn't use the entry point
```shell
$> singularity exec .datalad/environments/fsl/image bash -c export | grep FSLDIR 
$>
```
although it could be considered a "feature" helping to debug things etc, it actually at times can catch users expecting consistent environment between run and exec.

But it is possible to make use of ` /.singularity.d/env/` files in which are sourced upon exec as well I guess (didn't try yet). See https://singularity.lbl.gov/docs-environment-metadata#environment for more information.  I wondered if it might be a worthwhile approach, although it might create a "difference" between singularity and docker setups I guess.

**Comment by djarecka** [comment]
actually when I was testing it I got this:
```
[19:07][33.61][-7%]djarecka@openmind7:images_tests$ singularity run fsl_6.0.4.sif  export | grep FSLDIR
FATAL:   "export": executable file not found in $PATH
[19:07][33.80][-7%]djarecka@openmind7:images_tests$ singularity exec fsl_6.0.4.sif bash -c export | grep FSLDIR
declare -x FSLDIR="/opt/fsl-6.0.4"
```
