### ISSUE TITLE
potential name change

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#245]
the name `neurodocker` associates this package with neuroimaging / neuroscience and docker. this tool now supports singularity, and our goal is to support more than neuroimaging packages. a name change might be in order.

let's post individual names in comments below, and we can vote with thumbs up, thumbs down, or whichever other emojis convey your feelings.

(discussion began in #243)

cc: @yarikoptic @satra

**Comment by yarikoptic** [comment]
conteator  (**cont**ainer cr**eator**), ... when/if we meet - could pronounce (in a french/spanish? style)

**Comment by yarikoptic** [comment]
contistador (**cont**ainer conqui**stador**),  kinda like that it is almost plain conquistador

**Comment by satra** [comment]
i like contistador a lot

perhaps `reproenv` is quite appropriate for this! and we should move this project under the repronim umbrella anyway.

**Comment by yarikoptic** [comment]
reproenv is quite nice and simple.
The only one I found is dead (https://github.com/jmitchell/reproenv)... google search though happily finds "repro env" hits though so discovery on "who uses" might be tricky.  We have the same for datalad, for which google finds data LAD, data lab etc, requires imposing additional restrictions

**Comment by kaczmarj** [comment]
reproenv is nice. I think it summarizes the project well. A google search for reproenv already brings up the sfn and ohbn training presentations from repronim.

**Comment by kaczmarj** [comment]
closing this as the name "neurodocker" has withstood the test of time.
