### ISSUE TITLE
At least some minimal website/landing page

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#274]
ATM it seems I just need to point to this repository, which is IMHO suboptimal.  Would be nice if there was at least some at least minimal website (e.g. on readthedocs) with rendered examples etc

**Comment by kaczmarj** [comment]
@yarikoptic - i agree. i don't have much time to devote to this now, but i would like to see this happen too. i'll label this as help wanted for now.

**Comment by kaczmarj** [comment]
@yarikoptic - wanted to let you know that this is my priority at the moment. i'm also adding documentation of the python api (and improving the api).

**Comment by djarecka** [comment]
it already exists: https://www.repronim.org/neurodocker/index.html
