### ISSUE TITLE
[wishlist] add recipe for dsi studio

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#279]
http://dsi-studio.labsolver.org

There seems to be even some stale Dockerfile "project" for it suggesting that shouldn't be too hard:

https://github.com/maksteel/dsi-studio-docker/blob/master/Dockerfile

**Comment by mattcieslak** [comment]
I have a working version here: https://github.com/PennBBL/qsiprep/blob/master/Dockerfile#L106

DSI Studio changes a lot so I would not recommend trying to build directly from their github

**Comment by djarecka** [comment]
if there is still interest in this, please feel free to reopen
