### ISSUE TITLE
afni fails on example due to missing branch latest

### ISSUE THREAD

**Issue by ddwagner** [ReproNim/neurodocker#281]
First time using neurodocker, so maybe user error. But following the examples, I get a failure to build a singularity image for afni latest due to missing branch. 

command:

    neurodocker generate singularity --base=debian:stretch --pkg-manager=apt --afni version=latest method=source install_r_pkgs=true install_python2=true

error: 

    + cd /opt/afni-latest
    + git checkout latest
    error: pathspec 'latest' did not match any file(s) known to git.
    ABORT: Aborting with RETVAL=255

Fixed it by changing the singularity def file to checkout master instead but figured y'all might want to know.

**Comment by kaczmarj** [comment]
hi @ddwagner - this is a bug in neurodocker. thanks for bringing it to my attention. it seems like the afni installation in neurodocker is broken at the moment. i was going to suggest changing the version to `master`, but it looks like there are other problems unrelated to git. i am working on this now, and i hope to have a fix in the next few days.

you can also try `method=binaries` and `version=latest` if you don't mind pre-compiled binaries. those should be current.

**Comment by djarecka** [comment]
fixed #297
