### ISSUE TITLE
Make it possible to use eatmydata for at least apt

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#293]
resurrected versions of #60 and #268.  Every time I look at slowly scrolling reports from apt install I recall that they could have been notably faster with eatmydata.  If there is some fear of some kind of side-effects (of which I am personally not aware of), this could be an option to neurodocker, thus not enabled by default.

**Comment by kaczmarj** [comment]
@yarikoptic - yes it could be an option to prepend `eatmydata` to `apt-get install` calls. i would like to keep it optional though.

**Comment by stebo85** [comment]
this still seems like a useful addition?
