### ISSUE TITLE
Failed to open fsleyes

### ISSUE THREAD

**Issue by Joshuaalbert** [ReproNim/neurodocker#316]
I would like to use fsleyes/view. I built the singularity image following the instructions.
Then did
``` python
singularity shell my_nipype.simg
cd /opt/fsl-5.0.10/bin
fsleyes
```
The fsl logo flashes briefly then I got the error:
``` bash
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
   ERROR              main.py  382: initialise      - Unable to initialise OpenGL!
Traceback (most recent call last):
  File "fsleyes/main.py", line 379, in initialise
  File "fsleyes/gl/__init__.py", line 435, in getGLContext
  File "fsleyes/gl/__init__.py", line 577, in __init__
  File "fsleyes/gl/__init__.py", line 660, in __createWXGLCanvas
  File "/tmp/pip-build-Sf58Oz/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/wx-3.0-gtk2/wx/glcanvas.py", line 8, in <module>
  File "/tmp/pip-build-Sf58Oz/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: drmFreeDevice
```

System: Ubuntu 18.04

**Comment by kaczmarj** [comment]
hi @Joshuaalbert  - thanks for the report. i'm able to reproduce the issue. can you try the following commands?

```
docker run --rm kaczmarj/neurodocker:master \
  generate singularity \
  --base=debian:stretch \
  --pkg-manager=apt \
  --fsl version=6.0.1 method=binaries \
  --install libgtk2.0-0 libdbus-glib-1-2 > Singularity
sudo singularity build fsl_601.sif Singularity
singularity exec fsl_601.sif fsleyes
```

related to #294

**Comment by akemisetti** [comment]
I was getting the same error and try the above command and got the following error
============================
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 400 error_code 2 request_code 155 minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
=============================================
I got the same error when tried with docker.

Thanks
Anil

**Comment by djarecka** [comment]
if this is still an issue please reopen
