### ISSUE TITLE
centos:7 does not include libquadmath

### ISSUE THREAD

**Issue by dmd** [ReproNim/neurodocker#318]
When installing from:

`docker run --rm kaczmarj/neurodocker:v0.3.2 generate --base centos:7 --pkg-manager yum --fsl version=6.0.1`

After FSL is installed, most commands fail with:

```
error while loading shared libraries: libquadmath.so.0: cannot open shared object file: No such file or directory
```

because the package `libquadmath` is not included by default in `centos:7`

**Comment by kaczmarj** [comment]
@dmd - thank you for the report. you are using a very old version of neurodocker (from november 2017). can you please try with the latest version?

```
docker run --rm kaczmarj/neurodocker:0.6.0 generate docker \
  --base centos:7 --pkg-manager yum --fsl version=6.0.1
```

**Comment by djarecka** [comment]
looks like the issue was addressed
