### ISSUE TITLE
Update with fsl/6.0.0 and 6.0.1

### ISSUE THREAD

**Issue by bacaron** [ReproNim/neurodocker#320]
Hello,

I just recently discovered this repo and have loved how user friendly this is and how great it works!

I had one quick question: would it be possible to get FSL/6.0.0 and 6.0.1 added to the repo's capabilities?

Is it easy to change this locally?

Thank you,
Brad

**Comment by kaczmarj** [comment]
hi @bacaron - thanks for the kind words. fsl 6.0.0 and 6.0.1 should be available as of neurodocker 0.5.0
