### ISSUE TITLE
--entrypoint doesn't pass args correctly into (singularity) container 

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#330]
Depending on how defined it would not pass to singularity or to docker.

For singularity, `%runscript` seems to need to explicitly pass the `"$@"` into the entrypoint so they are not lost.

<details>
<summary>Running the following script which generates and invokes containers in both cases with entrypoint being /bin/ls shows that singularity does not pass my command line switches to ls </summary> 

```shell
$> cat ./generate_container.sh
#!/bin/bash

set -eu

ndversion=0.7.0
ndversion=master
cname=nd-test-$ndversion
sversion=$(singularity --version | sed -e 's,^.* ,,g')
simage=$cname-$sversion.simg 
echo "Docker: $cname  Singularity: $simage"

generate() {
	docker run --rm repronim/neurodocker:$ndversion generate "$1" \
		--base=neurodebian:buster \
		--pkg-manager=apt \
		--entrypoint /bin/ls
}

generate docker > Dockerfile
generate singularity > Singularity

echo "Docker:"
docker build -t $cname . > /dev/null || echo "built"

docker run --rm -v $PWD:$PWD $cname -l $PWD/$0

echo "Singularity:"
sudo rm -f $simage
sudo singularity build $simage Singularity >/dev/null 2>&1

```
</details>

```shell
$> ./generate_container.sh    
Docker: nd-test-master  Singularity: nd-test-master-3.5.2+ds1.simg
Docker:
-rwx--x--x 1 47521 47522 667 Apr 22 01:42 /home/yoh/proj/repronim/debug-containers/neurodocker/./generate_container.sh
Singularity:
Dockerfile  generate_container.sh  nd-test-master-3.5.2+ds1.simg  Singularity
./generate_container.sh  35.39s user 3.28s system 52% cpu 1:13.92 total
```

**Comment by yarikoptic** [comment]
FWIW, it could be just my overestimation of neurodocker powers, I assumed that it would be consistent between docker and singularity, but may be that is not intended.  So for now I just explicitly provide to singularity build additional "$@", so the script looks like
```shell
generate() {
    [ "$1" == singularity ] && add_entry=' "$@"' || add_entry=''

    docker run --rm repronim/neurodocker:$ndversion generate "$1" \
        --base=neurodebian:buster \
        --pkg-manager=apt \
        --entrypoint "/bin/ls$add_entry"
}
```

**Comment by kaczmarj** [comment]
neurodocker powers are limitless @yarikoptic. the difference in behavior between docker and singularity was not intentional (nor was it unintentional). `docker run` will pass in command-line arguments to the defined `ENTRYPOINT`, in essence overriding whatever `CMD` was. `singularity run`, on the other hand, will pass in command-line arguments correctly only if `"$@"` is added, like you indicate in your code example.

a solution to this would be to automatically append `"$@"` to `--entrypoint` when it is being used to generate a Singularity file. Would it be safe and appropriate to always add `"$@"` to an entrypoint?

**Comment by yarikoptic** [comment]
> a solution to this would be to automatically append `"$@"` to `--entrypoint` when it is being used to generate a Singularity file. Would it be safe and appropriate to always add `"$@"` to an entrypoint?

yeah, that would be the question. I am afraid that may be it would be overfitting for my particular use case where I am a dumb user just giving an entry executable, instead of me being a smart one providing a full command line specification and do not caring about docker being unable to handle that since I am just generating for singularity! ;-)  Some magic dust could be added by checking if entrypoint has unquoted space, thus suggesting it a complex command line statement and then not adding ` "$@"` but may be I am intentionally do not want to pass any parameters? ;-)  So, I think magic does not exist. We either leave it as is (with some additional docs) or would need some additional argument to disambiguate between those cases.

**Comment by kaczmarj** [comment]
i think we should leave it as is, and i will update the example on `--entrypoint`
