### ISSUE TITLE
Add MCR to Freesurfer installation

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#337]
Add MCR as in https://github.com/ReproNim/neurodocker/issues/333#issuecomment-624086581

MCR is required to get full use of freesurfer, including parts of recon-all. This can be added as an `--add-mcr` flag to the freesurfer installation. this would be a backwards-compatible change.

**Comment by stebo85** [comment]
that would still be nice to have. Does anyone have the bandwidth to work on this?

**Comment by Remi-Gau** [comment]
any hint how to smartly reuse what's in the matlabmcr template to do this?

https://github.com/ReproNim/neurodocker/blob/master/neurodocker/templates/matlabmcr.yaml
