### ISSUE TITLE
MRtrix 3

### ISSUE THREAD

**Issue by araikes** [ReproNim/neurodocker#338]
Love this tool. Just letting you know -- in case you don't know -- that the "full" release for [MRtrix 3.0](https://www.mrtrix.org/2020/04/23/mrtrix-3-0-0-has-arrived/) is out (no longer RC3).

**Comment by kaczmarj** [comment]
thanks @araikes ! i will update mrtrix in the coming days with the 3.0 binaries

**Comment by kaczmarj** [comment]
i compiled mrtrix3 on centos 6, and the built package is in https://github.com/kaczmarj/MRtrix3-builds/releases/tag/3.0.0

**Comment by yarikoptic** [comment]
FWIW 3.0 RCs were available from neurodebian for debian based systems.  Whenever someone from debian med team updates to 3.0.0 (filed an issue today asking for it) I will provide backports from neurodebian.

**Comment by tclose** [comment]
Any updates on this issue? How long does an update like this usually take the Debian team to make?

**Comment by yarikoptic** [comment]
as long as it takes.  Join the "fun" at https://salsa.debian.org/med-team/mrtrix3.git

**Comment by djarecka** [comment]
i think it was already resolved
