### ISSUE TITLE
FSL not fully functional?

### ISSUE THREAD

**Issue by loupl** [ReproNim/neurodocker#364]
First of all: thanks for providing this very helpful resource! 

Now to my question (potentially problem). I'm trying to use FSL for brain extraction via `BET`. I started by creating my own docker image using neurodocker and the nipype tutorial example, as I would like to embed this step in a larger workflow. 

When I try to run BET as is via `nipype`, e.g."
```
skullstrip = Node(BET(), name='skullstrip')
skullstrip.inputs.in_file = '/home/neuro/data/somones_T1w.nii.gz''
skullstrip.inputs.out_file = '/home/neuro/out/someones_T1w_BET-stripped'
skullstrip.inputs.output_type = 'NIFTI_GZ'
skullstrip.run()
```
it runs fine. However, the output isn't looking that great, so I wanted to explore and potentially use some of the additional options provided, e.g. the `reduce_bias` flag. This is where things stop running smoothly. If I add
```
skullstrip.inputs.reduce_bias = True
```
to the above (before `skullstrip.run()` of course), I get a relatively long error message of which the crucial bit is most likely this:
```
Image Exception : #22 :: ERROR: Could not open image /usr/share/fsl/5.0/data/standard/MNI152_T1_2mm
```
because I can navigate to this location but indeed no such image is there. 

Next I went to build a kind of minimal example using the following neurodocker command (based on the FSL example in the repository):
```
docker run --rm repronim/neurodocker:master generate docker\
	--base=neurodebian:stretch-non-free \
	--pkg-manager=apt \
	--install fsl vim emacs-nox \
	--add-to-entrypoint='source /etc/fsl/fsl.sh' \
	--user=neuro \
	--workdir='/home/neuro' > Dockerfile
```
and `docker build` subsequently. Then I run the image with the respective volumes mounted to provide the input data and store the output and then try to execute `BET` from the command line inside the container. 

1. I run it without the `reduce_bias` option like this:
```
bet /home/neuro/data/someones_T1w.nii.gz /home/neuro/out/someones_T1w_BET-stripped.nii.gz
```
which works fine. 
2. Then I run it with the `reduce_bias` option, which translates into a `-B` flag, like this:
```
bet /home/neuro/data/someones_T1w.nii.gz /home/neuro/out/someones_T1w_BET-stripped.nii.gz
```
and get the same error as above (with quite a bit following as before but this does not seem relevant).

So it seems like I am missing something rather obvious -- the template file FSL uses as part of its attempt to reduce bias. I went through the documentation and issues here on github and also did a quick search on neurostars but did not find anything relevant to help me fix this. I would guess it is a matter of providing this additional data? Am I missing some rather obvious step in the installation/documentation? Or would this be a matter of obtaining this atlas data and adding it manually when creating the docker image?

**Comment by kaczmarj** [comment]
Hi @loupl - thanks for the report. Can you please try installing `fsl-mni152-templates` in the image as well (https://neuro.debian.net/pkgs/fsl-mni152-templates.html).

Neurodocker installs apt package with the option `--no-install-recommends` to reduce image sizes. It's possible that the packages with data are recommended -- not required -- and therefore not installed.

You can see a full list of neurodebian packages at https://neuro.debian.net/pkglists/toc_all_pkgs.html. Search for FSL, and you will see many other packages with FSL data. If `fsl-mni152-templates` does not solve the issue, the data are probably in one of the other packages.

**Comment by loupl** [comment]
Thanks a lot for the quick reply @kaczmarj! This worked just fine and I can now run this particular step (`BET` with `reduce_bias=True`/`-B`) without any problem. 

This choice makes a lot of sense, I just wasn't quite sure what the best way would be to solve this small problem. I'll keep the neurodebian package list in mind for the future. 

Thanks again!
