### ISSUE TITLE
ANTs install issue?

### ISSUE THREAD

**Issue by dbkeator** [ReproNim/neurodocker#372]
Hi,
When adding ANTS to a docker image and then accessing various ANTs commands from within a bash script or similar inside the container faila.  It appears a trailing "/" isn't added to the ANTSPATH in the dockerfile and then just running an ANTS command complains about command not being found.  If one adds the trailing "/" to ANTSPATH in their dockerfile and then rebuilds the image everything is ok. 

Before dockerfile edit:  
ENV ANTSPATH="/opt/ants-2.2.0" \
After dockerfile edit:
ENV ANTSPATH="/opt/ants-2.2.0/" \

Cheers,
Dave

**Comment by kaczmarj** [comment]
thanks @dbkeator - this will be the first issue i tackle in 2021.
