### ISSUE TITLE
Simple Use Cases

### ISSUE THREAD

**Issue by dbkeator** [ReproNim/neurodocker#373]
Hi,

I'd like to request a few simple example use-cases that may help others use this feature for encapsulating scripts/workflows that were run on data at manuscript publication time.  Ideally one would set up the neurodocker images prior to running analyses.  In the case where one needs to share their workflow for publication but didn't use neurodocker from the start, it's been challenging to get the correct configurations needed to make things work.  So, I'm requesting a few simple use-case examples which I think will help others in a similar situation:

- Create an image that contains some neuroimaging software (doesn't so much matter which tools...freesurfer, fsl, ANTs) and uses one's custom bash script that reads data from the local filesystem (could be mounted storage), runs the custom bash script, and writes data back out to the local filesystem (which could be mounted storage).

-  Same as above but runs a custom python script (as part of the workflow) using python version X.X and has some additional python packages installed required by the custom python script.

- Not sure if this is consistent with best practices but an example (same as the above) but where we're adding the custom scripts to the docker image (which gets run automatically when the container is run) but the data is accessed from local disk and results are written back out to the local disk. 

- Same as previous example but now adding the actual data and the workflow scripts to the docker image.  In this example one would just do a docker run [image_name] and it automatically executes the custom scripts (bash or python) which accesses data embedded in the image and writes the results out to the local disk.  This is the black box mode where one doesn't need to see the scripts or the data really they just want to run the process, get a result, and check it against the published paper.

Thanks,
Dave

**Comment by kaczmarj** [comment]
thanks @dbkeator - these would be useful enhancements. i don't have time at the moment, but i can get to this over the next few weeks. if anyone reading this would like to contribute, please send a pull request :) i would really appreciate it.
