### ISSUE TITLE
Support for multi-stage builds in reproenv

### ISSUE THREAD

**Issue by aswinnarayanan** [ReproNim/neurodocker#387]
Hi neurodocker team

We have a number of images containing build artifacts, and I was wondering if we could streamline these using multi-stage builds.
I tried out a multi-stage implementation [here](https://github.com/NeuroDesk/neurodocker/tree/add/multi-stage) on our dev fork.

I saw that reproenv currently allows multiples base images. Is there plans for mutli-stage build support in the refactor?

**Comment by kaczmarj** [comment]
@aswinnarayanan - this should be possible in the refactor branch, but only using the python API. i thought about adding this to the command-line interface, but my thoughts at the moment are that adding multi-stage build support to the CLI would clutter the CLI and would not be useful for the majority of users.

here's an example of multi-stage builds using the python API. this is using neurodocker installed with

```
pip install https://github.com/ReproNim/neurodocker/tarball/refactor/migrate-to-reproenv
```

```python
from neurodocker.reproenv import DockerRenderer

dr = DockerRenderer(pkg_manager="apt")
dr.from_("debian:buster", as_="builder")
dr.from_("debian:buster-slim", as_="final")
dr.copy("/usr/bin/", destination="/opt/bin/", from_="builder")
print(dr)
```

this is the output:

```dockerfile
FROM debian:buster AS builder
FROM debian:buster-slim AS final
COPY --from=builder ["/usr/bin/", \
      "/opt/bin/"]
```

**Comment by aswinnarayanan** [comment]
Thanks @kaczmarj 
That works really nicely. How is the copy_from spec handled in the json output?

**Comment by kaczmarj** [comment]
the json output is being added to the refactor in #385 . the renderer classes have a `.to_json()` method that returns their build instructions as JSON. this conforms to the [renderer schema](https://github.com/ReproNim/neurodocker/blob/refactor/migrate-to-reproenv/neurodocker/reproenv/schemas/renderer.json).

the rendered dockerfiles (and singularity recipes) include an instruction to save info to a json file `/.reproenv.json`. that will tell a user how the container was made. and that json can be used to re-create the container with neurodocker.

i developed the json schema in tandem with the renderer classes. the renderer classes conform to a common API, and the json schema basically enforces this API. you will see that instructions have `name` and `kwds` keys. the `name` corresponds to a renderer instance method, and `kwds` are the keyword arguments to that method. take a look, for example, at the schema definition for the `FROM` instruction: https://github.com/ReproNim/neurodocker/blob/c2b1e242c9e9a0fa7d6729fde26b9d22274925f6/neurodocker/reproenv/schemas/renderer.json#L85-L114

```python
from neurodocker.reproenv import DockerRenderer

dr = DockerRenderer(pkg_manager="apt")
dr.from_("debian:buster", as_="builder")
dr.from_("debian:buster-slim", as_="final")
dr.copy("/usr/bin/", destination="/opt/bin/", from_="builder")
print(dr.to_json(indent=2))
```
and the json object

```json
{
  "pkg_manager": "apt",
  "existing_users": [
    "root"
  ],
  "instructions": [
    {
      "name": "from_",
      "kwds": {
        "base_image": "debian:buster",
        "as_": "builder"
      }
    },
    {
      "name": "from_",
      "kwds": {
        "base_image": "debian:buster-slim",
        "as_": "final"
      }
    },
    {
      "name": "copy",
      "kwds": {
        "source": "/usr/bin/",
        "destination": "/opt/bin/",
        "from_": "builder"
      }
    }
  ]
}
```

**Comment by aswinnarayanan** [comment]
Thanks @kaczmarj
