### ISSUE TITLE
Ensure calls to `ldconfig` are executed towards the end of `build` specifications

### ISSUE THREAD

**Issue by shnizzedy** [ReproNim/neurodocker#389]
> Number 7 in Singularity's [Support for Docker and OCI: Best Practices](https://docs.sylabs.io/guides/3.7/user-guide/singularity_and_docker.html#best-practices) is
> > Ensure calls to `ldconfig` are executed towards the end of `build` specifications (e.g., `Dockerfile`), so that the library cache is updated when the container is created.
> 
> As far as I know, neurodocker doesn't do that automatically (except for [in the AFNI installation](https://github.com/ReproNim/neurodocker/blob/a4940e311a260ccc863091812d4a3e89912ff632/neurodocker/templates/afni.yaml#L36)), so I just include `--run 'ldconfig'` as the final flag when I run `neurodocker`

_Originally posted by @shnizzedy in https://github.com/ReproNim/neurodocker/issues/321#issuecomment-812644282_

**Comment by djarecka** [comment]
the link to the best practice doesn't work. @kaczmarj - do you know where `ldconfig` should be added?

**Comment by kaczmarj** [comment]
@djarecka - this would mean running `ldconfig` (as `root`) somewhere towards the bottom of the dockerfile. so could look like this

```
USER root
RUN ldconfig
USER previous_user
```

the `USER` commands would only be necessary if we are not already root. neurodocker maintains state of which users are present, so we could make use of that.

**Comment by shnizzedy** [comment]
I fixed the link, and here are newer ones:
https://apptainer.org/docs/user/latest/docker_and_oci.html#best-practices-for-docker-apptainer-compatibility
https://apptainer.org/user-docs/3.8/singularity_and_docker.html#best-practices

**Comment by stebo85** [comment]
could be useful to do that. Would it be a good solution to create similar file to 
https://github.com/ReproNim/neurodocker/blob/master/neurodocker/templates/_header.yaml

and call it _footer.yaml

Then include things like this there?

There is also a note in _header about this:
# TODO: read this about locales http://jaredmarkell.com/docker-and-locales/

not sure if the idea was to add it to _header?

**Comment by kaczmarj** [comment]
_footer.yaml is a great idea.

i think `ldconfig` should be run at the end. but it would have to be run as root.

that note about locales is that i still find setting locales confusing... that TODO can be removed.
