### ISSUE TITLE
AFNI versions

### ISSUE THREAD

**Issue by djarecka** [ReproNim/neurodocker#397]
I don't remember why previous versions of AFNI are not available to install (`latest` is the only version allowed), could someone please remind me.

cc: @shnizzedy

**Comment by kaczmarj** [comment]
@djarecka - afni doesn't provide versioned binaries. neurodocker uses https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz

But as of right now, that file was modified on sept 27 2020, so it's not really "latest"...

```
file    2020.09.27.1244   linux_openmp_64.tgz
```

**Comment by stebo85** [comment]
@djarecka - Neurodesk tries to solve such problems by providing access to version controlled container versions of tools like AFNI: https://hub.docker.com/search?q=vnmd%2Fafni

You can explore what's available here: https://play.neurodesk.org/v2/gh/neurodesk/jupyter-neurodesktop-image/main?urlpath=neurodesktop
