### ISSUE TITLE
Wrong URL for SPM and missing library

### ISSUE THREAD

**Issue by arovai** [ReproNim/neurodocker#404]
Hello,
I was playing around with nipype_tutorial and encountered an error. The URL to SPM is outdated.
The steps to reproduce the error are as follows:
1. run `generate.sh`
2. run `sudo docker build -t test .`

Error is
```
(...)
Downloading standalone SPM ...
curl: (22) The requested URL returned error: 404 Not Found
(...)
```
Looking at the `Dockerfile` (and the one on the repo has the same issue) the address is
`https://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/dev/spm12_latest_Linux_R2010a.zip`
but there is nothing there.
Instead one should probably use
`https://www.fil.ion.ucl.ac.uk/spm/download/restricted/utopia/dev/spm12_latest_Linux_R2020a.zip`
Changing this by hand in the Dockerfile is however not enough, as now the build process gives an error
```
(...)
Downloading standalone SPM ...
/opt/spm12-dev/spm12: error while loading shared libraries: libmwlaunchermain.so: cannot open shared object file: No such file or directory
(...)
```
The `/opt/spm12-dev/spm12` thus seems to require `libmwlaunchermain.so` which is not installed in the image...

Peace out

ar

PS: the Dockerfile contains several instances of `2010` that refers to the old URL, so probably many things need to be adapted. But it is clearly healthier to solve this issue upstream in `neurodocker` instead of tweaking he Dockerfile, what do you think?

PPS: Specifying another SPM version in the neurodocker options might also be a better idea, e.g. building the Dockerfile generated by
```
neurodocker generate docker --base=debian:stretch --pkg-manager=apt \
  --spm12 version=r7219 method=binaries
```
produces no error.

**Comment by Brainarea** [comment]
Same problem here. Happens when --spm12 version=dev is used.
