### ISSUE TITLE
Is it possible to add a totally new template ?

### ISSUE THREAD

**Issue by akemisetti** [ReproNim/neurodocker#413]
What are the steps to add a new template?

**Comment by kaczmarj** [comment]
thanks @akemisetti - it is possible to add a new template. i have a pull request that makes this much easier.

@djarecka - do you think #378 looks ok to merge? once that's in, it will be much easier to add templates. that was part of my motivation in making that pr.

**Comment by Remi-Gau** [comment]
Sma

**Comment by Remi-Gau** [comment]
same answer as for #545
