### ISSUE TITLE
fsl 6.0.3 install failing

### ISSUE THREAD

**Issue by poldrack** [ReproNim/neurodocker#414]
Using the following command on Mac OS 10.15.7 with Docker version 20.10.6:

```
docker run --rm repronim/neurodocker:0.7.0 generate docker \
    --base debian:stretch --pkg-manager apt --fsl version=6.0.3
```

I get the following error:

```
#7 15.46 Downloading FSL ...
#7 654.4 Installing FSL conda environment ...
#7 664.4 Stage 1
#7 664.4 By installing this python distribution you agree to the license terms in
#7 664.4 /opt/fsl-6.0.3/fslpython/LICENSE.txt
100%64.4
#7 674.1 Stage 2
100%74.4
#7 743.2 /opt/fsl-6.0.3/etc/fslconf/fslpython_install.sh: line 206:  1439 Killed                  FSLDIR=$fsl_dir "${miniconda_bin_dir}/conda" env create -f "${script_dir}/fslpython_environment.yml" 2>> "${miniconda_install_log}"
#7 743.2       1440 Done                    | ${script_dir}/progress.sh 133 ${quiet} >> "${miniconda_install_log}"
#7 743.2 Failed to create FSL Python environment - see /tmp/fslpythonTwKA/fslpython_miniconda_installer.log for details
------
executor failed running [/bin/sh -c apt-get update -qq     && apt-get install -y -q --no-install-recommends            bc            dc            file            libfontconfig1            libfreetype6            libgl1-mesa-dev            libgl1-mesa-dri            libglu1-mesa-dev            libgomp1            libice6            libxcursor1            libxft2            libxinerama1            libxrandr2            libxrender1            libxt6            sudo            wget     && apt-get clean     && rm -rf /var/lib/apt/lists/*     && echo "Downloading FSL ..."     && mkdir -p /opt/fsl-6.0.3     && curl -fsSL --retry 5 https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.3-centos6_64.tar.gz     | tar -xz -C /opt/fsl-6.0.3 --strip-components 1     && sed -i '$iecho Some packages in this Docker container are non-free' $ND_ENTRYPOINT     && sed -i '$iecho If you are considering commercial use of this container, please consult the relevant license:' $ND_ENTRYPOINT     && sed -i '$iecho https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Licence' $ND_ENTRYPOINT     && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $ND_ENTRYPOINT     && echo "Installing FSL conda environment ..."     && bash /opt/fsl-6.0.3/etc/fslconf/fslpython_install.sh -f /opt/fsl-6.0.3]: exit code: 4
make: *** [build] Error 1
```

**Comment by award7** [comment]
I can't even get v6.0.3 to finish building.

**Comment by kaczmarj** [comment]
@djarecka @satra - could someone please help with debugging this issue?

**Comment by PatrikBey** [comment]
Hey 

I found the following installation instruction to work for FSL 6.0.4 inside the DOCKERFILE for my container:

```bash 

RUN wget -q http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py && \
    chmod 775 fslinstaller.py && \
    python2 /fslinstaller.py -d /opt/fsl -V 6.0.4 -q && \
    rm -f /fslinstaller.py

RUN rm -rf /opt/fsl/fslpython && \
   /opt/fsl/etc/fslconf/fslpython_install.sh -f /opt/fsl 

```

It only seemed to work for a Ubuntu:18.04 though not my previous 20:04.
Hope this helps.

**Comment by EvelinYin** [comment]
> Hey
> 
> I found the following installation instruction to work for FSL 6.0.4 inside the DOCKERFILE for my container:
> 
> ```shell
> RUN wget -q http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py && \
>     chmod 775 fslinstaller.py && \
>     python2 /fslinstaller.py -d /opt/fsl -V 6.0.4 -q && \
>     rm -f /fslinstaller.py
> 
> RUN rm -rf /opt/fsl/fslpython && \
>    /opt/fsl/etc/fslconf/fslpython_install.sh -f /opt/fsl 
> ```
> 
> It only seemed to work for a Ubuntu:18.04 though not my previous 20:04. Hope this helps.

I get the following error:
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no build stage in current context

**Comment by kaczmarj** [comment]
> > Hey
> > I found the following installation instruction to work for FSL 6.0.4 inside the DOCKERFILE for my container:
> > ```shell
> > RUN wget -q http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py && \
> >     chmod 775 fslinstaller.py && \
> >     python2 /fslinstaller.py -d /opt/fsl -V 6.0.4 -q && \
> >     rm -f /fslinstaller.py
> > 
> > RUN rm -rf /opt/fsl/fslpython && \
> >    /opt/fsl/etc/fslconf/fslpython_install.sh -f /opt/fsl 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It only seemed to work for a Ubuntu:18.04 though not my previous 20:04. Hope this helps.
> 
> I get the following error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: no build stage in current context

Try adding a `FROM ubuntu:18.04` at the top.

**Comment by JohannesWiesner** [comment]
Similar error here (script has been stuck at "stage 2" for more than 12hrs now):

![image](https://github.com/ReproNim/neurodocker/assets/48254290/89b6f44d-3288-431a-807f-8b9b2ec41d96)

This seems to be [documented on neurostars](https://neurostars.org/t/fsl-post-install-stuck-at-stage-2/22040/7)

**Comment by JohannesWiesner** [comment]
[This code section](https://github.com/aces/cbrain-containers-recipes/blob/master/FSL/Dockerfile.fsl_v6.0.5) (derived from [this comment](https://neurostars.org/t/fsl-post-install-stuck-at-stage-2/22040/7?u=johanneswiesner) on neurostars) worked for me.

**Comment by Remi-Gau** [comment]
For the record this is the case for all base image that we test on: 

https://github.com/ReproNim/neurodocker/blob/test_docker_build/docs/README.md#fsl
