### ISSUE TITLE
docker build jq failing -- potential race condition

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#415]
we build multiple docker images in parallel during tests. and after building each image, we clear the builder cache. it is possible that clearing the builder cache can disrupt other docker builds. 

https://github.com/ReproNim/neurodocker/blob/e9ff4f8a09cc9fb8ea66d86a53c2a5de2f909daa/neurodocker/reproenv/tests/utils.py#L79

```
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:17dc2ff3700540280bae3f5f4f67bc1cb071666936065ffc764766972d44ad06
Copying config sha256:793adb7e9abddf748359007f779345c8e4c83ecdcb235a48d54efbf53bd988a7
Writing manifest to image destination
Storing signatures
FATAL:   While performing build: conveyor failed to get: no descriptor found for reference "3a98eee344677acd4b5e12e5e42016deda58154fb3836bbe84953f8bcc8762f9"
```

at the end of all tests, we can clear the builder cache.

**Comment by Remi-Gau** [comment]
not sure if this is was still an issue but in any case I will add jq to the list of software we test the build of.
