### ISSUE TITLE
ANTS 2.3.4 not working

### ISSUE THREAD

**Issue by anagrammarian** [ReproNim/neurodocker#417]
When I try to run

docker run --rm repronim/neurodocker generate docker --base ubuntu:16.04 --pkg-manager apt --ants version=2.3.4
it fails saying
ValueError: URL not found for version '2.3.4'. Valid versions are 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.3, 2.0.0

It is easy to fix by running 2.3.1 and manually changing the dropbox location but will be nice to have it especially as it should be a simple fix.

Thanks,
manoj saranathan

**Comment by stebo85** [comment]
this is fixed now
