### ISSUE TITLE
Freesurfer singularity image building fails - easy fix

### ISSUE THREAD

**Issue by celstark** [ReproNim/neurodocker#420]
Building a singularity image of Freesurfer (tried 6.0.1 and 7.1.1) fails with thousands of:
` Cannot change ownership to uid 1623927, gid 1590: Invalid argument`
I've tried this with ubuntu and debian bases and in both the released 0.7 and git-based neurodockers:
`neurodocker generate singularity  
 --base-image debian:buster --pkg-mnanager=apt  
 --freesurfer method=binaries version=7.1.1 > freesurfer_nolicense_recipe`

The solution is simple, however - in freesurfer.yaml, line 80:
`    | tar -xz -C {{ self.install_path }} --owner root --group root --no-same-owner --strip-components 1 {% if self.exclude_paths -%}\`

Adding in the `--owner root --group root --no-same-owner` bit there.

**Comment by kaczmarj** [comment]
@celstark - thanks for the catch. would you mind submitting a PR?

**Comment by kaczmarj** [comment]
@celstark - #428 should fix this problem. would you mind trying out current master?
