### ISSUE TITLE
Mac Monterey zsh: command not found: neurodocker

### ISSUE THREAD

**Issue by keithcdodd** [ReproNim/neurodocker#427]
Hello, I assume I am missing something obvious (this is my first time working with Docker), but I cannot seem to use neurodocker. I installed Docker, and I verified that works, and running docker run --rm repronim/neurodocker:0.7.0 --help appears to work (although it exits almost immediately). 

However, after running that, neurodocker generate command does not work. It immediately errors out with zsh: command not found: neurodocker. 

I have been trying to read tutorials, example code, and past posts, but I cannot figure out what I am missing to be able to use neurodocker generate. Might it have something to do with Monterey (12.0.1) version of Mac?

Thanks!

**Comment by kaczmarj** [comment]
hi @keithcdodd - thanks for reaching out.

does the following command show a help message?

```
docker run --rm repronim/neurodocker:0.7.0 --help
```

if so, we can try a `neurodocker generate` command as follows:

```
docker run --rm repronim/neurodocker:0.7.0 generate docker --help
```

that should show a help message for the options available to build a docker image with neurodocker.

**Comment by keithcdodd** [comment]
OK yes, that works thanks! I assume I can just make a shortcut then in my ~/.bashrc for a command "neurodocker" to be short for "docker run --rm repronim/neurodocker:0.7.0" ? Unless you know a better method that works better with docker/neurodocker?

Thanks again!

**Comment by keithcdodd** [comment]
I think that making that shortcut (for mac I guess it is ~/.zprofile) seems to potentially work, but I am still running into issues, for example when attempting the FSL install example. 

First, it appears it now needs --base instead of --base-image (?), then it threw an error that fsl 6.0.4 was not a valid choice (but 6.0.3 and older is), an then finally I still get "failed to solve with frontend dockerfile.v0: failed to read dockerfile: error from sender: open .Trash: operation not permitted"

Should I maybe only be running neurodocker when in in root with admin privelages (sudo su), or is there some other way?

Thanks again. I know this may be unrelated, so I am happy to make another post if you prefer that!

**Comment by anneleenders** [comment]
Hello, 

I'm also a newbie and trying to install Neurodocker. I get the same error message. Did you find a solution in the end? 

Kind regards, 
Anne

**Comment by djarecka** [comment]
@anneleenders - could you please let us know which command are you trying to run?

**Comment by anneleenders** [comment]
Yes, it’s this command:
`docker run --rm repronim/neurodocker:0.7.0 --help`
The command from the neurodocker user guide. 
My software version is however not yet 12, I have OSX 11 installed.

**Comment by djarecka** [comment]
could you please copy the full error? I think you could actually have a different problem than the original one.

**Comment by anneleenders** [comment]
Good morning :) 

This is what is in my terminal:

```
Last login: Thu Jan  6 08:01:03 on ttys002
(base) anneleenders@MacBook-Pro-AEMLeenders ~ % docker run --rm repronim/neurodocker:0.7.0 --help
usage: neurodocker [-h] [-v {debug,info,warning,error,critical}] [-V]
                   {generate,reprozip} ...

Neurodocker is a command-line interface to generate custom Dockerfiles and
Singularity recipes.

For help generating Dockerfiles and Singularity recipes, run

$ neurodocker generate docker --help
$ neurodocker generate singularity --help

optional arguments:
  -h, --help            show this help message and exit
  -v {debug,info,warning,error,critical}, --verbosity {debug,info,warning,error,critical}
  -V, --version         show program's version number and exit

subcommands:
  valid subcommands

  {generate,reprozip}
    generate            generate recipes
    reprozip
(base) anneleenders@MacBook-Pro-AEMLeenders ~ % docker images
REPOSITORY                       TAG       IMAGE ID       CREATED         SIZE
anneleenders/docker101tutorial   latest    7f8decf5bc53   9 months ago    27.9MB
docker101tutorial                latest    7f8decf5bc53   9 months ago    27.9MB
alpine/git                       latest    a939554ad0d0   10 months ago   25.1MB
repronim/neurodocker             0.7.0     0b700323c695   21 months ago   81.5MB
(base) anneleenders@MacBook-Pro-AEMLeenders ~ % neurodocker generate docker --pkg-manager apt \
    --base-image neurodebian:buster \
    --ants version=2.3.4 \
    --miniconda version=latest conda_install="nipype notebook" \
    --user nonroot
zsh: command not found: neurodocker

```

**Comment by djarecka** [comment]
In order to use `neurodocker` command directly from command line you would have to install neurodocker python package:
```
# installing with pip
pip install neurodocker
# checking if the command works
neurodocker --help
```

Alternatively, you could just use neurodocker image to use the software, e.g. `docker run --rm repronim/neurodocker:0.7.0 --help`, and this works for you. You can also use the image to run `generate` command, e.g. `docker run --rm repronim/neurodocker:0.7.0 generate dokcer --help` (instead of `neurodocker generate docker --help`)

Please let me know if that helps

**Comment by anneleenders** [comment]
Thanks a lot! This helps indeed. 
(except for the minor typo in the generate docker) You might want to edit that for people who are reading this later an copying :)

**Comment by djarecka** [comment]
I will close this for now. @keithcdodd please reopen if you still have issues
