### ISSUE TITLE
FreeSurfer 7.1.1-min template is missing

### ISSUE THREAD

**Issue by dfslezak** [ReproNim/neurodocker#429]
Hi. I am trying to generate FreeSurfer version 7.1.1-min but template with URLs only have 6.x.x versions.
Do you have the updated template for newer versions?

Thanks in advance

**Comment by kaczmarj** [comment]
can you try the current master version? 7.1.1-min is listed here:

 https://github.com/ReproNim/neurodocker/blob/483ead1e9cf5e2004128b92bf9b3f86e5c9d5453/neurodocker/templates/freesurfer.yaml#L27

**Comment by dfslezak** [comment]
Thanks. Got it!

**Comment by kaczmarj** [comment]
great - i will close this issue now. please open a new issue if you run into any other problems.
