### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by satra** [ReproNim/neurodocker#439]
should we cut a new release?

there is a post on neurostars that seems like errors due to mismatch in versions: https://neurostars.org/t/creating-nipype-tutorial-using-neurodocker/21646

**Comment by kaczmarj** [comment]
yes let's cut a new release. i think now is a good time. i'll cut the release tomorrow.

**Comment by satra** [comment]
thanks @kaczmarj - do you mind just responding to that neurostars thread if you have a bit of time.

**Comment by kaczmarj** [comment]
@satra - will do! thanks for the pointer

**Comment by kaczmarj** [comment]
i have not forgotten about this -- haven't had a chance to release. will try tomorrow or over the weekend.

**Comment by kaczmarj** [comment]
i released version 0.8.0!
