### ISSUE TITLE
An option to add a prefix to all commands in the dockerfile

### ISSUE THREAD

**Issue by civier** [ReproNim/neurodocker#440]
Hi Jakub, Satra, and all,

Does Neurodocker have an option to add a prefix to all commands in the dockerfile?
I want to add "set -vx &&" to the beginning of all commands, but don't know how?

Thanks ahead,
Oren

**Comment by kaczmarj** [comment]
@civier - neurodocker does not provide a way to do this. but how about processing the generated dockerfile with something like `sed`?

for example

```
sed 's/RUN /RUN set -vx && /g' Dockerfile
```

**Comment by civier** [comment]
Yes. I can do the sed thing, but I think it could be a useful option also for others. I will implement it when I have a chance.
BTW, doesn't Docker build have any flags that can control the shell that runs the recipe commands + the argument for the shell? For what I need, it might be easiest to implement it at that level.
