### ISSUE TITLE
manifest for repronim/neurodocker:0.8.0 not found

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#442]
Quick cross check: am I the only one to get this when trying to use the version 0.8.0 ?

```
docker pull repronim/neurodocker:0.8.0

Error response from daemon: manifest for repronim/neurodocker:0.8.0 not found: manifest unknown: manifest unknown
```

Everything is fine when using `latest` but I believe that from the tags on docker hub the latest will be 0.7.0 (as confirmed by the warnng when trying to use the latest image).

FYI: tried this when I saw that the latest release on the repo is 0.8.0.

**Comment by kaczmarj** [comment]
@Remi-Gau - thanks, looks like 0.8.0 is not on dockerhub.

@djarecka - dockerhub isn't automatically building containers for neurodocker. i don't have admin rights on the dockerhub page -- could you please see what's wrong? at the very least we should build a neurodocker:0.8.0 image and push it manually.

**Comment by kaczmarj** [comment]
@djarecka or @satra - can you please give me push access to https://hub.docker.com/r/repronim/neurodocker/ ?

my dockerhub id is kaczmarj

**Comment by satra** [comment]
unfortunately we don't have a proper team membership and it's limited. if you setup a github workflow for push, i can put in the token authorization for the repronim bot.

**Comment by stebo85** [comment]
we had the same problem in the Neurodesk project and also solved it by using one account with the account details stored as github secrets:

maybe it helps - here is an example:
https://github.com/NeuroDesk/neurocontainers/blob/master/.github/workflows/afni.yml
https://github.com/NeuroDesk/neurocontainers/blob/master/.github/workflows/build-docker.sh


the important bits are:
```
env:
  DOCKERHUB_ORG: ${{ secrets.DOCKERHUB_ORG }}
```
```
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_ORG != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name : Run docker builder + Upload to docker and github registry
        run: for IMAGENAME in "${IMAGELIST[@]}"; do /bin/bash .github/workflows/build-docker.sh $IMAGENAME; done
```

**Comment by Remi-Gau** [comment]
closing this as the images can now be pulled from @kaczmarj docker hub repo
