### ISSUE TITLE
Support for invalid-Python-keyword labels in API

### ISSUE THREAD

**Issue by tclose** [ReproNim/neurodocker#444]
Label names in Docker can have '.'s in them (e.g. `org.nrg.commands` is a special label used in XNAT's container service) but the syntax of
the API, i.e. `_Renderer.label(label_name=label_content)`, doesn't support that

**Comment by tclose** [comment]
Could this be handled by adding a `labels` method that takes a dictionary of labels to add, e.g. `_Renderer.labels({'label_name': label_content})`?

**Comment by kaczmarj** [comment]
@tclose - good catch. it's a little clunky, but for now could you try

```python
_Renderer.labels(**{"label.name": "label_content"})
```

but i agree that labels with `.` in them should be supported. your proposed solution would be great. prs are welcome ;)

**Comment by kaczmarj** [comment]
can we close this now that #453 has been merged?
