### ISSUE TITLE
Neurodocker

### ISSUE THREAD

**Issue by ConorOW** [ReproNim/neurodocker#446]
Hey team.

Created a Neurodocker container (v0.7.0) with FSL and Mrtrix3:

`neurodocker generate docker --pkg-manager apt --base debian:stretch --fsl version=5.0.11 --mrtrix version=3.0_RC3 > ConPipe.Dockerfile`

Works great until it gets to a step (`dwibiascorrect`) which appears to need Python, as it breaks with the following error:
`/usr/bin/env: ‘python’: No such file or directory`

Tried amending my Dockerfile but have so far been unsuccessful, so wanted to write to see if you all had any ideas.

Cheers,
Conor

**Comment by stebo85** [comment]
Dear @ConorOW 

can you try 

   --mrtrix3 version=3.0.3 method="source" 

You could also quickly test if the mrtrix3 Neurodesk image works for you (contains fsl_6.0.3 and mrtrix 3.0.3):
docker pull vnmd/mrtrix3_3.0.3:20210917


I hope that works :)

Cheers
Steffen

**Comment by ConorOW** [comment]
Thank you so much Steffen, the first suggestion worked perfectly!

Very grateful for your help,
Conor
