### ISSUE TITLE
docker image not building automatically on DockerHub

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#448]
The neurodocker docker images on dockerhub are not building automatically. i do not have push privileges so cannot update the images there. can someone please upload a 0.8.0 docker image? the ideal solution would be to fix the autobuild.

cc: @djarecka

**Comment by stebo85** [comment]
@djarecka - are you still looking into this issue? Or is this solved by now?

**Comment by kaczmarj** [comment]
the images are building on every push to master and every release. closing this issue.
