### ISSUE TITLE
Freesurfer installation overwrites the PATH environmental variable

### ISSUE THREAD

**Issue by ellisdg** [ReproNim/neurodocker#449]
After creating a docker image, I noticed that the directory locations for any package installed before Freesurfer were not listed in the PATH environmental variable.

Looking at the [template for FreeSurfer](https://github.com/ReproNim/neurodocker/blob/65067b63335c782265fec32d46253c7eae2e80ba/neurodocker/templates/freesurfer.yaml#L57), it looks like it completely overwrites the PATH variable instead of simply prepending the Freesurfer directory locations [like FSL does](https://github.com/ReproNim/neurodocker/blob/65067b63335c782265fec32d46253c7eae2e80ba/neurodocker/templates/fsl.yaml#L82). Is there a reason for this?

**Comment by pwighton** [comment]
Hi @ellisdg, thanks for pointing this out.  I just submitted a PR (#462) that should fix this issue.
