### ISSUE TITLE
FSL installation takes long

### ISSUE THREAD

**Issue by mateuszpawlik** [ReproNim/neurodocker#450]
This is not a neurodocker question but may be relevant. I think it is a more FSL or conda question. However, I though about asking here for some hints because FSL support is tedious with their mailing list.

I'm trying to build a Docker container with FSL. The "Stage 2" of "Performing post install tasks" takes forever. It's not my Internet connection. Maybe someone here has a similar experience.

Here's the part installing FSL:
```
FROM debian:stable
...
WORKDIR /opt
# Install FSL for pydeface
# file command is used by FSL installer
RUN apt-get -y install file
RUN curl -s https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py -o fslinstaller.py
RUN python3 fslinstaller.py -d /opt/fsl -V 6.0.5
RUN rm fslinstaller.py
# Variables and config for FSL.
ENV FSLDIR="/opt/fsl"
RUN . ${FSLDIR}/etc/fslconf/fsl.sh
ENV PATH="${FSLDIR}/bin:${PATH}"
```

I narrowed it down to the following command:
```
/opt/fsl/fslpython/bin/python /opt/fsl/fslpython/bin/conda-env create -f /opt/fsl/etc/fslconf/fslpython_environment.yml
```
However, it doesn't do much but creates a conda environment.

<details>
<summary>
Here are the contents of `/opt/fsl/etc/fslconf/fslpython_environment.yml`.
</summary>

```
name: fslpython
channels:
 - conda-forge
 - defaults
 - https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/channel
dependencies:
 - eddy_qc=1.0.3
 - fmrib-unpack=2.8.0
 - fsl-add_module=0.3.2
 - fsl-get_standard=0.1.0
 - fsl_mrs=1.1.8
 - fsl-pyfeeds=0.9.5
 - fsl_sub=2.5.7
 - fsl_sub_plugin_sge=1.4.7
 - fsl_sub_plugin_slurm=1.3.7
 - fsl-tirl=v2.1.3b1
 - fsleyes=1.3.0
 - fslpy=3.7.0
 - ipython=7.23.1
 - matplotlib=3.4.2
 - mkl-service=2.3.0
 - nidmresults=2.1.0
 - nidmresults-fsl=2.2.0
 - nibabel=3.2.1
 - nilearn>=0.7.1
 - numpy=1.20.3
 - pandas=1.2.4
 - paramiko=2.7.2
 - pip=21.1.1
 - python=3.8.6
 - pyyaml=5.4.1
 - scikit-image=0.18.1
 - scikit-learn=0.24.2
 - scipy=1.6.3
 - seaborn=0.11.1
 - vtk=9.0.1
 - wire=1.0.0
 - wxpython=4.0.7.post2
```
</details>

**Comment by mateuszpawlik** [comment]
An update. I've tried version 6.0.2 and it went through but with error:
```
[OK] Installer updated to latest version 3.2.3
[OK] Installer self update successful.
Downloading...
Checking FSL package        
[OK] File downloaded
Installing FSL software version 6.0.2...
[OK] FSL software installed.
Performing post install tasks
Stage 1
By installing this python distribution you agree to the license terms in
/opt/fsl/fslpython/LICENSE.txt
100%
/opt/fsl/etc/fslconf/fslpython_install.sh: line 188: /opt/fsl/fslpython/bin/conda: No such file or directory
/opt/fsl/etc/fslconf/fslpython_install.sh: line 189: /opt/fsl/fslpython/bin/conda: No such file or directory
/opt/fsl/etc/fslconf/fslpython_install.sh: line 190: /opt/fsl/fslpython/bin/conda: No such file or directory
/opt/fsl/etc/fslconf/fslpython_install.sh: line 191: /opt/fsl/fslpython/bin/conda: No such file or directory
Stage 2
100%
Failed to create FSL Python environment - see /tmp/fslpythonvQ5d/fslpython_miniconda_installer.log for details
Post install setup failed
[OK] Post installation setup complete
Error processing tar file(exit status 1): write /opt/fsl/data/first/models_317_bin/R_Late_bin.bmv: no space left on device
```

**Comment by mateuszpawlik** [comment]
This issue may have some hints: https://github.com/easybuilders/easybuild-easyconfigs/issues/7899

**Comment by mateuszpawlik** [comment]
Update. I changed `RUN python3 fslinstaller.py -d /opt/fsl -V 6.0.2` into `RUN /usr/bin/python3 fslinstaller.py -d /opt/fsl -V 6.0.2`. It didn't change anything.

**Comment by mateuszpawlik** [comment]
Cześć @kaczmarj :-) Thanks for the tip. Yes, I've seen this post but I'm trying to install FSL in Docker, so executing these steps is a little bit problematic. But I will try it next.

With version 6.0.2, Stage 2 doesn't last long. I think it stalls in newer versions because something goes wrong. I'm really surprised that the FSL developers don't fix these issues. But well, it is what it is.

Small update. I've added
```
ENV FSLDIR="/opt/fsl"
RUN [ -d "$FSLDIR/fslpython" ] && rm -r $FSLDIR/fslpython; \
    $FSLDIR/etc/fslconf/fslpython_install.sh -f $FSLDIR

```
as indicated in [Troubleshooting section](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation#Troubleshooting:_commands_missing_after_installation) but it didn't change anything.

**Comment by mateuszpawlik** [comment]
> https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;bd0fa8bf.2004 might have the answer. the problem could be that fsl is not downloading the miniconda installer correctly. the potential fix is as follows...

Funny thing, the `-L` option is in the newer FSL version of `fslpython_install.sh` but not 6.0.2. I added it in 6.0.2 and now "Stage 2" stalls as originally. That's the current Docker snippet:
```
# Install FSL for pydeface
RUN echo "INFO Installing FSL ..."
# file command is used by FSL installer
RUN apt-get -y install file
RUN curl -s https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py -o fslinstaller.py
RUN /usr/bin/python3 fslinstaller.py -d /opt/fsl -V 6.0.2; \
    rm fslinstaller.py
# Try solution from https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;bd0fa8bf.2004 
ENV FSLDIR="/opt/fsl"
RUN sed -i "s/dl_cmd_opts=\"--fail\"/dl_cmd_opts=\"--fail -L\"/g" $FSLDIR/etc/fslconf/fslpython_install.sh
RUN [ -d "$FSLDIR/fslpython" ] && rm -r $FSLDIR/fslpython; \
    $FSLDIR/etc/fslconf/fslpython_install.sh -f $FSLDIR
# Variables and config for FSL.
RUN . ${FSLDIR}/etc/fslconf/fsl.sh
ENV PATH="${FSLDIR}/bin:${PATH}"
```

**Comment by kaczmarj** [comment]
>I added it in 6.0.2 and now "Stage 2" stalls as originally

the stall is normal. conda takes its time to create the environment :) from my experience, it could take around 15 minutes or more for the conda installation to complete. please let me know if your docker build succeeds

**Comment by mateuszpawlik** [comment]
I've built a Dockerfile using Neurodocker with `neurodocker generate docker --pkg-manager apt --base-image debian:stable --fsl version=6.0.2 > Dockerfile.nd.fsl` It finished building but I don't have a detailed timestamp. It was less than 2.5h.

I'll try my Dockerfile again. It seems FSL takes a long time to install.

**Comment by kaczmarj** [comment]
i think the neurodocker build is the way to go. but unfortunately, fsl does take a long time to install. first, the fsl binaries have to be downloaded, and then the conda environment has to be created. both of these processes take some time as you have seen. these will go slower is the internet speed is low.

regarding the progress `Stage 2 0%`, in my experience the percentage did not increase until the very end of the process... so i wouldn't rely on that as a marker of whether the installation has stalled. you could look at `htop` or your computer's activity monitor to see what processes are going on in the build.

**Comment by mateuszpawlik** [comment]
I'd like to thank you @kaczmarj for help. I've build the Docker container using mine and Neurodocker-generated Dockerfile, both for FSL 6.0.5.1 Both work. Both take around 2.5h to install FSL (**not** due to the Internet bandwidth).

I generated Nerodocker Dockerfile with `neurodocker generate docker --pkg-manager apt --base-image debian:stable --fsl version=6.0.5.1 > Dockerfile.nd.fsl_6.0.5.1`.

Snippet from my Dockerfile:
```
FROM debian:stable
...
# Install FSL for pydeface
RUN echo "INFO Installing FSL ..."
RUN curl -s https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py -o fslinstaller.py
RUN /usr/bin/python3 fslinstaller.py -d /opt/fsl -V 6.0.5.1; \
    rm fslinstaller.py
# Variables and config for FSL
ENV FSLDIR="/opt/fsl"
RUN . ${FSLDIR}/etc/fslconf/fsl.sh
ENV PATH="${FSLDIR}/bin:${PATH}"
```

**Comment by kaczmarj** [comment]
@mateuszpawlik - i'm glad it's working now.

one note on the line `RUN . ${FSLDIR}/etc/fslconf/fsl.sh`. the sourced variables will not persist to future instructions. each `RUN` instruction starts up its own shell and then tears down that shell when it's finished.

you could get around this in two ways: either source the `fsl.sh` file when you start the container, or hardcode the environment variables in `fsl.sh` with `ENV` instructions.

**Comment by mateuszpawlik** [comment]
Thank you for that. It would most probably hurt later :wink:
