### ISSUE TITLE
Make --no-install-recommends optional

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#458]
My use case is to recreate elderly python2 environment with python-mvpa2 via `apt` on neurodebian:nd100.  That package for "full featured" operation Recommends a good number of packages. I want to have them installed, but neurodocker hardcodes addition of `--no-install-recommends` into apt invocation.  Even adding `--install-recommends` in the list of packages (cheating) causing the line to be `--no-install-recommends --install-recommends ...` unfortunately does not provide a workaround :-/

**Comment by kaczmarj** [comment]
i'm not sure if this is documented anywhere, but you can use `--install opts="" wget` to remove `--no-install-recommends`.

```
docker run --rm -it kaczmarj/neurodocker:0.8.0 generate docker -p apt -b neurodebian:nd100 --install opts="" wget
```

does that work for you?

if this isn't documented, we should include it somewhere.

**Comment by kaczmarj** [comment]
following up on this. does `--install opts=""` satisfy your needs @yarikoptic  ?

**Comment by yarikoptic** [comment]
oh, and it needs 0.8.0 (0.7.0 isn't good enough)!  seems to work, but requires invocation change (--base-image vs --base) and output is different (https://github.com/ReproNim/containers/commit/30b39e96f30e52f4dc598c038918240d69b89c11) so will analyze in detail later. Feel free to close as is or close with adding some docs about this magical feature ;-)

**Comment by stebo85** [comment]
<img width="688" alt="image" src="https://github.com/ReproNim/neurodocker/assets/4021595/47259b88-dd07-4023-a911-62e2ef76f016">
this is documented - so closing this issue
