### ISSUE TITLE
MRtrix 3.0.3

### ISSUE THREAD

**Issue by araikes** [ReproNim/neurodocker#467]
Currently, _neurodocker_ only supports MRtrix up to v. 3.0.2, but there are some useful updates in 3.0.3. Any objection if I submit PR that adds 3.0.3 as an option?

**Comment by kaczmarj** [comment]
Hi, please do submit a PR!

Best,
Jakub

**Comment by djarecka** [comment]
@araikes - are you still planning to work on it?

**Comment by araikes** [comment]
I want to get back to this but haven't had a chance to yet. There are some issues with OS version and dependencies for MRtrix `3.0.3` and `3.0.4` but I cannot remember offhand what all issues I had.

**Comment by stebo85** [comment]
has anyone looked at adding newer versions of mrtrix?

**Comment by Remi-Gau** [comment]
Will give it a go.
I think I may have figured out why the install from source of mrtrix is failing.
will PR for both.
