### ISSUE TITLE
Freesurfer-7.1.1-min neurodocker ERROR: could not configure recon-all parameters

### ISSUE THREAD

**Issue by nichy-consortium** [ReproNim/neurodocker#472]
Hi,

I am experiencing issues when running recon-all in the freesurfer-7.1.1-min neurodocker container. The container was built using the instructions provided on the website (https://www.repronim.org/neurodocker/user_guide/examples.html)

To generate & build:
```
neurodocker generate docker \
 --pkg-manager apt \
 --base-image debian:buster-slim \
 --freesurfer version=7.1.1-min \
 > Dockerfile
```

`docker build --tag freesurfer:7.1.1-min --file Dockerfile .`

Then I tried running recon-all from within the container with:
```
docker run -it -d \
-v /path/to/license/license.txt:/opt/freesurfer-7.1.1-min/.license \
-v /path/to/subject/data:/opt/freesurfer-7.1.1-min/subjects \
-e SUBJECTS_DIR=/opt/freesurfer-7.1.1-min/subjects \
--name test1 image_ID bash
```

`docker exec -it test1 recon-all -subjid SUBJECTS_DIR/sub1_T1w -i SUBJECTS_DIR/sub1_T1w.nii.gz -all -notify log_done.txt`

The error that shows up after the docker exec command is:
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
LookupError: unknown encoding: ANSI_X3.4-1968

Current thread 0x00007fd3cc546740 (most recent call first):
Abort
ERROR: could not configure recon-all parameters
```

The recon-all input arguments look correct. The error is a bit vague overall so I am not sure where to start. Do you know how this can possibly be solved? Any help would be greatly appreciated!

Thanks in advance,
Eva

**Comment by kaczmarj** [comment]
@nichy-consortium - which version of neurodocker are you using?

looks like the problem is with the locale encoding. can you try setting the environment variable LC_ALL to something like `en_US.utf8` ?

so add this to your `docker run`: `-e LC_ALL=en_US.utf8`

if that doesn't work, try these values instead: `C` or `C.utf8` or `en_US`
