### ISSUE TITLE
local module load in docker run

### ISSUE THREAD

**Issue by yidilozdemir** [ReproNim/neurodocker#474]
Hello all, maybe not appropriate to ask here but, how does one build a local python package in the miniconda/pip environment in the docker run command line? Or should one build and start the docker, build the package by referencing to the local working directory where the module exists, then save this image?

**Comment by kaczmarj** [comment]
hi @yidilozdemir - could you give some more information? and does this have to do with neurodocker?

if i understand correctly, here is how i would approach this. copy the local python package into the docker image (use the `COPY` instruction in the dockerfile), and then use `RUN` to install the package. here is some pseudo-code:

```
WORKDIR /opt/my-python-package
COPY . .
RUN pip install .
```
