### ISSUE TITLE
--fsl error

### ISSUE THREAD

**Issue by JonteP** [ReproNim/neurodocker#475]
I am trying to build a docker container including FSL like so:

`docker run --rm kaczmarj/neurodocker:0.9.1 generate docker --pkg-manager apt --base-image neurodebian:buster --fsl version=latest --miniconda version=latest conda_install="nipype notebook" --user nonroot > Dockerfile`

and get this:
FSL is non-free. If you are considering commercial use of FSL, please consult the relevant license(s). Proceed? [y/N]: Aborted!

The problem is I have no chance of answering 'y', it is automatically aborted. I tried piping echo y | to this command but it did not work. Anyone else encoutered this?

**Comment by satra** [comment]
try adding `-i`, so `docker run -i --rm ...`

**Comment by JonteP** [comment]
Thank you, satra! That was embarrasingly simple...

**Comment by ysagon** [comment]
It is maybe embarrassingly simple but I had the same question and was about to open the same issue! So thanks. And probably it would worth to do an update of the documentation:)

**Comment by satra** [comment]
would one of you be up for sending a PR ? there is a known issue with using the docker `-t` flag and it could be added there, but this seems more about general guidance than an issue. perhaps could be a note at the first point docker is mentioned. perhaps here: https://www.repronim.org/neurodocker/user_guide/installation.html#container-preferred

**Comment by stebo85** [comment]
I created this change in the documentation - can others check if the changes in the installation section and the example page for FSL are good?
