### ISSUE TITLE
Issue installing latest version of ANTs

### ISSUE THREAD

**Issue by arianayoum** [ReproNim/neurodocker#480]
Hi, I was building my docker image but I am getting this error:
**Cloning into '/tmp/ants/source'...
HEAD is now at 6c729710... Updating version for release v2.4.2
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.16.3..3.19.7 or higher is required.  You are running version 3.7.2**

This is my docker recipe:

_#!/bin/sh

set -e

generate() {
    docker run --rm repronim/neurodocker:latest generate "$1" \
    --base-image neurodebian:stretch-non-free \
    --pkg-manager=apt \
    --install ants afni \
    --ants method=source version=2.4.2 \
    --afni method=binaries version=latest \
    --freesurfer version=6.0.0 \

}

generate docker > Dockerfile_

The error is essentially saying I need to update my cmake but I'm not sure how to do that

**Comment by kaczmarj** [comment]
Can you try with a newer base image? Perhaps a neurodebian bookworm image? Or neurodebian buster? Stretch is relatively old now.

Best,
Jakub

**Comment by stebo85** [comment]
Dear @arianayoum,

Agree with @kaczmarj - neurodebian:stretch-non-free is too old and the latest 
cmake that comes with it causes the issue you see.

In the www.Neurodesk.org project we build ants 2.4.2 successfully in a ubuntu 22.04 container: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/ants/build.sh

Cheers
Steffen

**Comment by araikes** [comment]
If it's any help, I added a PR (#473) a bit ago to enable installing not from source as they are now officially releasing pre-compiled versions.

**Comment by djarecka** [comment]
@araikes - have you had a chance to try it with a newer distribution of neurodebian as it was suggested? Do you still have this issue?

**Comment by araikes** [comment]
@djarecka,

I didn't have an issue. This was originally @arianayoum's issue. 

My PR (#473) was merged so that zip files are being utilized for the current versions of ANTs rather than building from source. This should eliminate the need for CMake in general when generating containers with ANTs (after 2.4).

As an addendum here, I need to update this as ANTs `2.4.2` and `2.4.3` are now available as well whereas my #473 only covered `2.4.1`

**Comment by djarecka** [comment]
sorry, wanted to ping @arianayoum if we can close it.

**Comment by arianayoum** [comment]
Yes you can close it. Thank you so much!
