### ISSUE TITLE
versioning support

### ISSUE THREAD

**Issue by satra** [ReproNim/neurodocker#481]
@stebo85 and @kaczmarj - perhaps we need to do something around minimal versions of OS in our templates. we should consider what is needed to ensure future compilation of a current dockerfile. we could perhaps do this through a CI process for common bases and tools, and recommend those. ccing @djarecka since something like testkraken could be used to just evaluate builds.

**Comment by kaczmarj** [comment]
great idea @satra . i tried to do something like that https://github.com/ReproNim/neurodocker/tree/add/test-all-templates but it got stale a while ago.

**Comment by stebo85** [comment]
Agree, that would be a nice feature. Would it make sense to include a list of working base operating systems? I found that most recipes only work optimally in a small subset of OSs.

**Comment by Remi-Gau** [comment]
Would it make sense to let ci test the build and have a dashboard of badges of all the builds so we can see what works?

Is that your branch was trying to do @kaczmarj?

**Comment by kaczmarj** [comment]
@Remi-Gau - yes that's what my branch was trying to do. i was trying to generate a table of successful builds and the base images / versions of software.

again, i really appreciate the pr. neurodocker has needed this for a while but it requires tremendous effort.
