### ISSUE TITLE
FSL recipe generation never completes

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#485]
tried to run the following and nothing ever happens

the command never terminates

```bash
docker run --rm -it kaczmarj/neurodocker:0.9.1 \
        generate docker \
                --base-image bids/base_validator \
                --pkg-manager apt \
                --fsl method=binaries version=6.0.3 > Dockerfile
```

**Comment by Remi-Gau** [comment]
Using older version of neurodocker lead to build that end up with never completing either.

https://github.com/bids-apps/base_fsl/issues/4

**Comment by satra** [comment]
this is running into a prompt that requests acknowledgment for noncommercial use. if you type `y` it should complete.  however, this is a bug. 

- the prompt doesn't show up even when `-it` is specified in docker.
- fsl should have an option to accept the license to disable the interactive prompt.

**Comment by Remi-Gau** [comment]
Thanks for the the tip.

Managed to create a Dockerfile with the latest version but it fails to build:

https://github.com/bids-apps/base_fsl/blob/master/Dockerfile

https://app.circleci.com/pipelines/github/bids-apps/base_fsl/7/workflows/8d8e934d-e759-4de1-8fa0-7b11211b4509/jobs/15


FYI: the base image for this is is the following on that is based on the latest ubuntu.

https://github.com/bids-apps/base_validator/blob/master/Dockerfile

**Comment by satra** [comment]
i'm pretty sure this has something to do with the fsl conda installation. there is a separate thread on this #450 . it may be worthwhile for fsl to move to mamba instead of conda. i don't know why the install times are that crazy. the only thing i can think of is time to resolve conflicts. an alternative would be to hack the fsl python install script and try.

**Comment by satra** [comment]
it could be a function of the base image, but i could not get it to build even manually. the fsl python installation fails for this version. any chance of switching to a debian base image, which may be more stable [old].

**Comment by Remi-Gau** [comment]
how far back in time should I go?

because this CI workflow tells me that the problem might not be a distro issue:

https://github.com/Remi-Gau/neurodocker/actions/runs/3863737433

**Comment by Remi-Gau** [comment]
using the `--yes` flag solves this for most distro
