### ISSUE TITLE
update online docs and readme + clarify dockerhub tags

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#494]
the current readme and online docs reference neurodocker version 0.7.0. we should update the docs to reference a more recent version like 0.9.1.

we should also clarify the dockerhub tags and specify that `:latest` is a moving target -- it points to the latest stable release.

```
repronim/neurodocker:latest -> latest release (0.9.1 now)
repronim/neurodocker:master -> master branch
repronim/neurodocker:0.9.1
repronim/neurodocker:0.9.0
repronim/neurodocker:0.8.0
repronim/neurodocker:0.7.0
...
```

related to https://github.com/ReproNim/neurodocker/issues/489#issuecomment-1382899709

**Comment by kaczmarj** [comment]
also update the docs to indicate that minification does not work on M1/M2 macs. Related to #497 .

**Comment by djarecka** [comment]
@sooyounga - could you please update the doc with these suggestions
