### ISSUE TITLE
BUG: repronim.org/neurodocker not found

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#503]
https://www.repronim.org/neurodocker used to work (yesterday or the day before) and today leads to a 404.

**Comment by satra** [comment]
where are the pages being built? i don't see a gh-pages branch.

**Comment by kaczmarj** [comment]
i don't know. i don't think we have had a gh-pages branch. looking at [the pages settings for neurodocker](https://github.com/ReproNim/neurodocker/settings/pages), the docs are being built from `/docs`. but perhaps the sphinx pages are not being built properly. maybe it's time to set up a github action for this.
