### ISSUE TITLE
using copy command in Neurodocker leads to failed to process "'": unexpected end of statement while looking for matching single-quote error

### ISSUE THREAD

**Issue by stebo85** [ReproNim/neurodocker#504]
I am using the neurodocker command "copy" to add a readme file to the containers being build:

   --copy README.md /README.md \

Since the latest changes in neurodocker this step now fails with

Step 23/26 : COPY ["(",       "'",       "R",       "E",       "A",       "D",       "M",       "E",       ".",       "m",       "d",       "'",       ",",       " ",       "'",       "/",       "R",       "E",       "A",       "D",       "M",       "E",       ".",       "m",       "d",       "'",       ")"]
failed to process "'": unexpected end of statement while looking for matching single-quote

Does anyone by any chance have an idea what that could be?

It might also be totally unrelated to neurodocker and caused by any other recent changes - just wondering if anyone has an idea before I spend more time on this rabbit hole :p

**Comment by Remi-Gau** [comment]
Should have been patched today already in version 0.9.4.

**Comment by satra** [comment]
@stebo85 - before you update can you quickly check that your previous command now raises an exception about a bad version?

**Comment by stebo85** [comment]
ahh, wonderful! 

Both things are working:

0.9.3 gives a warning:

WARNING: The candidate selected for download or install is a yanked version: 'neurodocker' candidate (version 0.9.3 at https://files.pythonhosted.org/packages/82/ac/47382cd88ba5dafb8c4f052ef423052d822c4bb24a2bcb67e44bace4b299/neurodocker-0.9.3-py3-none-any.whl#sha256=e7cf18baa41a387437d08cfd634ec9de628844c4ba5ecf8fb16de0c7134c60a8 (from https://pypi.org/simple/neurodocker/) (requires-python:>=3.8))
Reason for being yanked: Bug in --copy and --entrypoint options

and 0.9.4 fixed the problem :)

Sorry - I should have tried updating first

Thank you
Steffen
