### ISSUE TITLE
Parsing of entrypoints

### ISSUE THREAD

**Issue by Engrammae** [ReproNim/neurodocker#507]
Hey!
I would like to add `ENTRYPOINT ["bash", "-c"]` to my Dockerfile using the neurodocker option `--entrypoint TUPLE`. I tried adding it with and without quotation marks (`--entrypoint bash -c`. `--entrypoint "bash" "-c"` or `--entrypoints 'bash' '-c'`) but I get the following error:
```
Usage: neurodocker generate docker [OPTIONS]                                                                            
Try 'neurodocker generate docker --help' for help.

Error: No such option: -c 
```
I guess the parameter `-c` is interpreted as an option of the `generate docker` command.

This can be reproduced by running the following script:
```
generate_docker() {
    docker run -i --rm repronim/neurodocker:0.9.4 generate docker \
        --base-image neurodebian:stretch-non-free \
        --arg DEBIAN_FRONTEND='noninteractive' \
        --pkg-manager apt \
        --entrypoint "bash" "-c"
}

generate_docker>Dockerfile.Test
```
If one could get this to work these lines could be a workaround for #506 :
```
RUN echo 'source activate csp' >> /home/csp/.bashrc`
ENTRYPOINT ["bash", "-c"]
```

**Comment by kaczmarj** [comment]
hi @Engrammae - thanks. the command line interface seems to be interpreting '-c' as a new option instead of a string literal value. for example this works `--entrypoint bash c` but this does not `--entrypoint bash -c`.

this is related to https://github.com/pallets/click/issues/249 but i do not see an easy way to get around this. the linked issue mentions `--` but i do not know where that would fit in with our command line.

**Comment by Engrammae** [comment]
Hi @kaczmarj ,
thanks for your reply! 
As far as I understand, the issue you linked adressess how to pass arguments that begin with a hyphen and tell click that this is an argument and not an option. In this case we would need to tell click that a parameter is an option value belonging to an option and that it's not another option.
While it is [documented](https://click.palletsprojects.com/en/8.1.x/arguments/#option-like-arguments) how to handle  the setting described in the linked issue, I could not find anything in the documentation of click for our case. 
If I am reading the [code](https://github.com/ReproNim/neurodocker/blob/c92634f38d0e5489cd9171fafc827a4e18aac0fc/neurodocker/cli/generate.py#L221-L226) correctly, the option `--entrypoint` currently uses the option type [Tuples as Multi Value](https://click.palletsprojects.com/en/8.1.x/options/#tuples-as-multi-value-options). Could maybe the option type  [Multiple Values from Environment Values](https://click.palletsprojects.com/en/8.1.x/options/#multiple-values-from-environment-values) be of help? Maybe one could add another option `--entrypoint-from-environment`?
