### ISSUE TITLE
--yes option doesn't do anything?

### ISSUE THREAD

**Issue by JohannesWiesner** [ReproNim/neurodocker#508]
Just discovered that in our current script, the `--yes` option does not have any effect on the generated Dockerfile. See this issue: https://github.com/JohannesWiesner/csp_docker/issues/12#issuecomment-1406501104

**Comment by kaczmarj** [comment]
hi @JohannesWiesner the `--yes` flag is meant for any alerts that a neurodocker template might have. for example, the fsl template alerts the user that fsl is non-free software for commercial purposes. see https://github.com/ReproNim/neurodocker/blob/c92634f38d0e5489cd9171fafc827a4e18aac0fc/neurodocker/templates/fsl.yaml#L13

without the `--yes` flag, the user will be prompted to agree by typing `y`. with the `--yes` flag, the yes response is automatic.

https://github.com/ReproNim/neurodocker/blob/c92634f38d0e5489cd9171fafc827a4e18aac0fc/neurodocker/cli/generate.py#L389-L398 

perhaps we can rename the `--yes` flag to clarify its purpose.

**Comment by JohannesWiesner** [comment]
Aaah, interesting, then I got that totally wrong. Yup, the docs are quite sparse, maybe we should update the docs? 

```
docker run -i --rm repronim/neurodocker:0.9.4 generate docker --help
  --yes                        Reply yes to all prompts.
```
