### ISSUE TITLE
freesurfer 7.4.1

### ISSUE THREAD

**Issue by hjbockholt** [ReproNim/neurodocker#541]
Hiya,
I tried to branch and edit the freesurfer.yaml, but I dont have branch/PR access on this repo.
I'm happy to contribute to this project if you'd like as my team is starting to regular use it.
thanks,
jb

**Comment by kaczmarj** [comment]
hi @hjbockholt - thanks very much! to contribute, you can fork this project and then you will have your own copy which you own. you can branch there, make changes, and then submit a pull request back to this repository. let us know if you need any help. we appreciate your contributions!!

**Comment by hjbockholt** [comment]
thanks, most of projects we usually just do branches rather than forks, but thanks, I did a fork and suggested a PR.
happy to help whenever I can.
