### ISSUE TITLE
add instructions for making a new template

### ISSUE THREAD

**Issue by kaczmarj** [ReproNim/neurodocker#545]
Currently, I point people to the ANTs recipe to show them how to add a new recipe. We should add a workflow for how one adds a template. This should also include a commented yaml file.

**Comment by Remi-Gau** [comment]
don't we have this already: https://github.com/ReproNim/neurodocker/blob/master/docs/user_guide/add_template.rst#add-software-to-neurodocker

I know I am not the average user but I could find my way around with it

**Comment by kaczmarj** [comment]
yes that's true. thanks @Remi-Gau . i will close this issue.
