### ISSUE TITLE
unclear why python 3.10 is more required to pass than latest python

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#553]
![image](https://github.com/ReproNim/neurodocker/assets/6961185/fb59a4d4-8fc9-4812-a1fc-daeee255c166)

**Comment by kaczmarj** [comment]
This is because I set 3.10 as required when 3.10 was the latest python. The “required” label can be removed.Best,JakubOn Aug 22, 2023, at 06:42, Remi Gau ***@***.***> wrote:﻿

**Comment by kaczmarj** [comment]
i have removed python 3.10 from the required set. now none are required explicitly.
