### ISSUE TITLE
do not test the builds on ubuntu 16:04 and debian stretch

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#555]
this may be kinder to our CI as it would dramatically reduce the size of the multiverse we are currently "exploring"

the question is also: do we want to support those "old" base image?

https://github.com/ReproNim/neurodocker/blob/9e235e0c55e797d8a1585fbe911a6e9de6766668/.github/workflows/create_workflows.py#L31-L38

**Comment by stebo85** [comment]
agree, that limiting the tests to the latest base images would make sense: reducing the load on testing and encouraging security best practices.
