### ISSUE TITLE
`pip install -e .dev` fails in CI

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#561]
see here

https://github.com/ReproNim/neurodocker/actions/runs/6003705019/job/16282726469?pr=560#step:4:1

**Comment by stebo85** [comment]
I have a look at it now

**Comment by stebo85** [comment]
I think that adding the python version should have fixed that, but I couldn't test it yet

**Comment by Remi-Gau** [comment]
seems to be fixed
