### ISSUE TITLE
add possibility to only "dispatch" the bootstrap workflow for a given software

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#567]
![image](https://github.com/ReproNim/neurodocker/assets/6961185/fb264534-a1b4-48af-8b56-a4c19af52ed0)

currently I have to run all the softwares when I just want to test conda...

see here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#providing-inputs

**Comment by Remi-Gau** [comment]
OK this one is actually done now

**Comment by stebo85** [comment]
amazing work :)
