### ISSUE TITLE
Update docker image and pip versions to latest 

### ISSUE THREAD

**Issue by ddwagner** [ReproNim/neurodocker#599]
Hi,

Any chance the docker hub image and the pip version can get updated to the latest? The current versions don't support Freesurfer past 7.2.0 though the github repository has templates for 7.4.1. I can work around it by cloning the repo but it's a lot easier for singularity/apptainer users if there was a docker hub image we could use.

Thanks!

**Comment by Remi-Gau** [comment]
@satra @stebo85 @kaczmarj @djarecka 
who's got the "make a release" superpower on this repo?
