### ISSUE TITLE
Add support for versioned binary installs of AFNI

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#600]
I want a specific version to get it reproducible, tried

```
  --afni method=binaries version=24.0.17 \
```
but then it crashes with
```
❯ ./generate_container.sh ; docker build -t dsst-temp .
Traceback (most recent call last):
  File "/opt/neurodocker/neurodocker/reproenv/renderers.py", line 77, in _render_string_from_template
    source = tmpl.render(template=template)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 13, in top-level template code
jinja2.exceptions.UndefinedError: 'dict object' has no attribute '24.0.17'
```

looking at the template, there is only one 

```
  urls:
    latest: https://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz
```

and that https://afni.nimh.nih.gov/pub/dist/tgz/ contains only those latest builds.

@afni-rickr @afniHQ -- is there an "official" archive of binary AFNI builds somewhere to add support for here?

**Comment by stebo85** [comment]
It looks like https://afni.nimh.nih.gov/pub/dist/tgz/AFNI_ARCHIVE/ contains all older builds

**Comment by afni-rickr** [comment]
We have internal backups, not named by tag, but no externally reachable storage of all compiled packages.
The AFNI_ARCHIVE directory contains only snapshots of distributed src trees, which are probably better retrieved via git and tags.
We will revisit this, thanks.
