### ISSUE TITLE
failure of the auto-release workflow

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#606]
https://github.com/ReproNim/neurodocker/actions/runs/8535839752/job/23383085547

**Comment by stebo85** [comment]
Do we know what causes this? I also just had that error:

ℹ  info      Using command: 'shipit'
d6acf65470576d7f154eb13baa01e1a2dfc6aa1f
ℹ  info      Getting commits from HEAD^ to HEAD
37d1b03bed90cde459ddef874e0b504e811080c6
d6acf65470576d7f154eb13baa01e1a2dfc6aa1f
d6acf65470576d7f154eb13baa01e1a2dfc6aa1f
fatal: ' 9007199254740991': not an integer

Error: fatal: ' 9007199254740991': not an integer

**Comment by satra** [comment]
The version of intuit auto needs to be upgraded.
