### ISSUE TITLE
Congrats to everyone -- we released 1.0.0 (watch the labels!)

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/neurodocker#618]
With the fix
- #617 

we got

![image](https://github.com/ReproNim/neurodocker/assets/39889/dece7bc9-b43d-4317-9de5-765fb49163a6)

![image](https://github.com/ReproNim/neurodocker/assets/39889/4148031f-9468-451d-ba7e-09f660838532)

I guess due to

![image](https://github.com/ReproNim/neurodocker/assets/39889/49213d59-e444-43be-b008-92140b860099)

which had `major` label.

Similar happened to us in other project(s) but we took it as a "motivational feature" not a "bug".  **BUT** it is important to attend to labels for the PRs from dependabot.  Or someone needs a workflow which would kick `major` label for PRs from dependabot (@jwodder?)  . References

- https://github.com/dependabot/dependabot-core/issues/3465
- https://github.com/intuit/auto/issues/2412

**Comment by kaczmarj** [comment]
i think we deserve to be at 1.0.0 :)

but yes, we need to watch out for dependabot's labels

**Comment by jwodder** [comment]
I gave my advise about this problem before in https://github.com/datalad/datalad-installer/issues/175#issuecomment-1793053369.
